#include <list>
#include <vector>
#include <pthread.h>
#include <cstring>
#include <jni.h>
#include <unistd.h>
#include <fstream>
#include <iostream>
#include <dlfcn.h>
#include "Tools/Includes/Logger.h"
#include "Tools/Includes/obfuscate.h"
#include "Tools/Includes/Utils.h"

#include "Tools/SOCKET/client.h"
#include "Tools/SOCKET/IncludeClient.h"
#include "Widgets/ImportWidgets.h"
#include "Tools/DrawTools/Draw.h"
#include <chrono>
extern "C"
JNIEXPORT jstring JNICALL
Java_com_vivek_Menu_imageBase64(JNIEnv* env, jobject thiz) {
    return env->NewStringUTF(OBFUSCATE("iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAABmE0lEQVR4nOWdB7hdRdX3f7PLqbffm94bBEILCUV6kS6IoBQBBaSJFZQiSHsVkaqoiAovCGLBTu+9hRpCSSGkkZ7cXk7de8/3rJl9bkmhCCi+3/gcc7n3nH32nlmzZpX/+i+llNL81w4Vv+zQ8ijaMT87OKA8tHLRCpT51wPlopTf+z47NKgQpTWaAC0fiEKgjIpkeiLQkflv824V0Tdr8v3yH/+d0+jxXzUqk135OR7yK6VQ2re/V4rI8cDxUciCu2jHB5VAmX8rguP0XUsF6ChC6wAlQhCGEJXQIhhRhCIkUo4RBCXCoLW9GxVuYPH73+cne/wXCYBdNDvt/RbPyIEDjoNSCbPjzWO58kqhVNIuvpcA+dmNBcNJolUCIhGQCK2KZsEJCij5V5chLFkhkH/DEioS7VAGHRpB0Mi/DlqJZlCxthBhqiz+J18IvP+OxRb1q1Fml1duWXa1/M0F17U725EdnjALrpwU2kkTOdU4VKPcerRXh+PVoRJDiJJ1KN9DifCEIarUiS6thWILOuhAhW3gdKDpBhEOtwi6iNJldFSEMEDJMaFLKO3G96fROrSCET/GJ/2AVZ88G6Ci2kUAZJcrs8uUI+Ig57hrBMMuuLySZvdrEYwwhYMIQD1OpgldOwY1eCzukFE4Q4cRDa5HD2lANVbjNjgkasB3IC/r2aGJ2orQ2gVrW2H1SvTqd9ArV6HXrkC3ryUqrEJFrWhZdD9AqZBINIJoDPOSo6FsjwhEQ1RsBWtjfBLHJ0gA4t1udlNs0JkbFMNNtpJrdpr2fHCTKO0QBaJ2U7heLU7DKNTIKTibbInefBOi8aNQQ+tR9aCT8TfI4gQ5wmIRp1zCE5UeaSKtiRI+JJOQTOG4GWtDyC0VgVbQy9tQC5agZs8lmv86LHmTqGUZQdgNflnsTWNAqqBgjwdzVMhREtrF1/Z4sOItAvLJGJ8AAYh3vFGfjp0i5aBxcc3C+70GndlRJVl0H5Vpwh2/NWqbnVFTdkRtuhnUixYA3bEKtWwxevF89Mp56FUroLWNqKsDcnl0EECgIQpQYWRMCCNwrtiJHqQyqJoaVFMjashI1PDJMG4TGDUO1TDMvr+1jHr9daKZzxLNfBG99E3CcjP4GrFFlbEbRAgCIwjiXxhhIDS67ZMyPiECIFMiZ6hnznkxTXTv2Z4gCiJUUMZNNOFtOh1n5wNh+n7okYPlWEYtnYd6YwZ69rOEC15DtSwhKrTGSljHR4kcF465pjEYHdE0laUQYRB1rY0nYH6OxLCThQsRsXRI4qZq0YNH4U7aDrbZBbbcFT16pPEQvfkLiJ68h+jpxyktnY2mB5IiwBVjsiIMgfkeeyxE/78LgCyMWXqUkmn20I5ddKNTS0UcrXGHTMTZ+bM4ux1NMHESqiPCee1x9At3Eb75BOGa+UC3Mb0UPspNEnl2oeU75LiwFrmIg1XE8r9IhMAqgL7zWk4h+WWsmOzvtXEFCeS8L1tVL291a3HHTMGddiDsfihqmymERXCeewp1918pvfIoUakFkuJlaFS5ZOwH60EERgCsvdDPpf3/SwAqVr5vBUAW3vWJigUz9cnx2+IccCp6t8+jsgmiF15EP3ULeub9hO0LehWpdlLgivEXn7Giba2THrvk/WIHomE0OKJt/DoTMArK7XEcwHoc/adErHoi64/gSnCJWFNoCPIoHcSmagJv/A7ofY6CfY5FDa/Bmb0A/acbKT15L2FpFSTlnYERBPk3imMO/0l38T8iAL3unbh1eCjXunBRqYynA/xNtkcd8i3Y/lCiXABP/A712K8oL34h3uWgvZS1C0STml1UmUa7uzc0zPHiKLQISy7HTid9l6qx43nw+9/BybhE4uvLbo+vZ65ZUdd9h0X8LTb41CtxYdnEC4w4Z4fg7XwE0ZHfgi0m4Ly5mOiWnxE+fTdh2EKUSuIEEncoxm6jCMLA7/k/KgDymGJpiSEkqtkFP2MmWZWLJEZOwT38W0R7HAurc0T3XEv05K+IOt6xU+MlcJRddHtwVBZo3W+pGJb9Ywmxfnc98/l0ZggHPfIwpdHDeHzXA+l66wV0SqHCAML+15Qvk0jgQAGw3yNDnqf/LwIQVU+E61bj7XQE6uhzibaciDtjJvrmKyjNfpzILaEkjhGUiJQcC5Uj4d8bRfwPCIAYemLw+WYnUsrjpxvxDz6N6LDvo4oa/c+rCR+6Ct29xipIP2UmprLZzPKvs/DWeBw4ZPG1sS3sKW/ekcgS5XoY+t1LmXDBNxEFs/yfD9Ny0jGEaZHNoonoVa5vbYA+AVh/9D/DrS1jThL5RFDA0SGuU4W75/Hw5YtgaBPuHX+ifNsVlDoWoHyJRoo2CNCSe/g3a4J/mwBoscIrET0vY350wwKJbQ/COeFKSkMm4j3we6J//pBSy1zzTsdLm4W1Wlh8643dqo0SrmdM6cqC2LNbuz6qHJIcvxWJe++lLpUmVw7oyiZJHHcyXQ/+GdIJxJIzUT5ZUOO6beRbe+8n1i4VQTRHWxwGlO8PJHpYIpEdjH/49wmO+AaqtRn1y3Mpz/irCX1E8pyh2D4VIahc979eAPrCupKUEQudchE33UDi6AsIP/tVeOMt1K1fpzTvIfvIiaw9FsTyjseGF18WXmIGDq7jGqPKLEVsWRv7QP4Vb0Am2Evg5UNS1/+ewucPIpuHsgs5FVH1+lsUDzuQsNxFhI379xeAii0g3+c4DqEYhub8Xl/zVLRR/39Fh1DusQ7ppN1wTvoFwdZbkrjjd5RvvphiYS34njEsbfAozkJ+3EIgAvDxvjyNSmjl+Fp5WRF2nR63i85cMV+nbtc6fehlOullzO/xUlr5ae14We24KfNSTnKDL5ykdpyEVl619pODNNRqN9Wg8au1ks+a98k1kho3o51ktVYkdXrXw3VyfqjVaq2rbn9WV1/5e+2s0tp5R+uqE/9Hu6S0k2w0nzGfi+/D3IuX0m6yTptoj5PVjnxX5X5UIn7O9e/Vlc+58lwZrfyMkaSEl9Hpwy7TqTu1zvxsjk6P2VM7JDWJeq1UWqNcrczL+VjX52MWAAnguxonYSbQw9HpPb+hkzdqnfrREp2etI946Oa9ZtG9qt7FX2/BlS9nR/ySn2Vi0xoSevPdj9J7fOYrGlm8VL12jRBYATHXcjNG+Hy/Vmf+/LJWb2mdmlvSmR0O0am6sTozY41WcyKdeWatTg/eTCuV0o4n10hrx8loVwRJhDfdoMHT20zfW+9y2Onm77KwlfsSYVfm3kQYBt6/uRfPCrfrV2nlGHNPpzc/SKd+06xTfyzqzE4naJe0xm/QysnYuTMC4PwXC4CTMjsm4WZ19vhf6tRftE6f/DftpxvNBCgvrZWf1cqr6t1x6y9+Ip5kN37FWsXsdE/7w3bXZz3epU+/8DKjCXCrtJuo1Y4TX0smHKWzJ35fu29ozetaV11zj/ap14qErj7tUu3P1dp9Veuai27TvnzOtbvbcdLaS1Rr/FojYIcdc7y+/OV2Xf+pr2sHRyuvslCVHev2aoP+r15BcFOxRshawQSdqh+rU99/Uqfu1jp72OXaQb67Visn2++6/1UCYFUXbkIrHJ3KDtXZMx/Qyd9pndn/IqvuZfH9pMazi++46fdYdKfftSvHSkK7MqHJJp38xuv6ine0vvTvd+tswyQJ9WhXdrE5JlJaUkm1F92qvRla80RRZx5aodOjttLJxGCd+dOrWj0XaPcZrWuve0YnErV9C+ZnjQD7iSH6Oz/9tf7dKq2bftKmqd/CCI9oGhy5tz4BsELQ/2XvV172OBFBkCMmq0lkjRAk3ZTOfOnXOnmX1umTfqc9NUjj1GjlVI6D/woBqEyEYybGPFj9OJ29eJZO/kbr9NZflKStVq5nz0+/SuNn7E4YsPNlsvzeha+8+n+H+bvjmXPVV0p7h/2vTl1R1D9ZHOkb5i7U0z59iPmbmWyxLZSnk7XDdfpPSzUPB9qdpXXVBbfomuMvtFrhvqJOPZjT6Qk7mtCSUdfm3K7Rk7fdVf/6uZf1n1q0briqqN1TZmjfr9YY9S/3UVHTfa+++64IgT0aep/RHE1pjVejlV+tXeVKDkln9/++Tv9Z68zpd2rPG6SVEg0jr4/nGHA+YpPSpHMNICMskho0GeeshwhrJ+Jc9mlKs/5A4ImznYnfK5a+/BTGcCzxv63Fbe1m639XXnbE1rixkCUfHxFoTWLZM5R0grOuauPJ1nEM+cqPUW7KQvkkbOumiDpWEM1+GTyXcHmJ4j7HUP7yeYRLBfCRwHl7CcHi2eb+IuOBaOPHDzr5al5Ib8upV66htTtBatlzlMtdNuZoxKW/7165v8qr4gfZ69lnlFCyYBAlzFy0KWknTeAlKN7/Q9S1XyP61MEkTv4drpOOjfV0nNT6xCKCYnfI8XHCAsnBW8J370HrLFy5J8UVL4BfJc69AV0qXbAxdRPVk2FdPjtR7zXioG8lPiDe8+KZ+O05ilENv7sjgq61JIrthF7GJGKcoIQj8YeaTaFVBMKhnHMo6wSqGKELksYdglM/GKd5IdrLmjvxyl089dxynloyDVpq8JqgPP+J2M2UvMF7AT363Dj7bP1EWdLfsgMEOyDgFtKEnkvpmV+S6MkRnn4z/gm/hZu+TIjkHCRLWhoQd/iw4yMUKUHpJNBRQKJ+U5zv3Il2qtDX7EtZFj9RTaSS8Y3Ljq98rlcC1ttF7z76aQQJtrTOQ61YgBN6uKsj0o1TcaccgBN0o4z/XcI/5HuE9ZNRLQFO3kF1a5wuUD0uTkdIyanH++wl+IkkSnZ4uQt39HSStTvjrpVIbQq1phW94vU43Px+Ejnra4e+vEL82ViQJXCldRLtVVN89bc4vzoBtdNn8I/7tQUmCy6CxEe6bB9NIEjMOoFaK0hmBuGcfT9R4zi4dA+CFc8TJurN300KVAARJjduAzYVtS/HQCVl+wEfAa2SqChPYq+bKI86gai1iKpP4g9rx135R9DNuMN2pzRkN8oqRFe5KD9CpePAa14b2J/u1niBS3LVa0TL7sXxkkSNx1BoHYzOFXFrknjtjxPcta+NLhqY+L8yfXYB7SdFCzh9OAiDPBY0Ugk36Mbf+dtEp/0E5++/pPyP7xJK+DySiKFogk/CESBmhIAxlYdHEufUWwhGboZ36WfIr3geZPFFM1S2vEHOOjadGg9Rg30K7d1Vm4mq9YsQVnaUUYpLn0c1nQD5AF1yCbqqCUd9FWpjLEZLAaodSETopEQGjTwaVJAuKlTRIeoqkfe3gnFbCcSAaIU2oEEVllHJJOqd54hk4QVR3G/tDWDVhK3fr0DY56zYPDY7WtkEkihLoT1F6ZmfkqoeTnj0WSSal1F86moiL40WkIwKPvRx8OEEQJwr2dlOCjcIcI+5nHD7PXAvP4nSgnvAbwBHsn1hDJaUV2j+O5lKU8zl1kuzvp8hodj+Ey3aw2Ty17wInQGqWECrAjrKEr1ThloHNcxDDU+BILqGgGqA2mprR7TJMSC4v1XAMpdoWYReU0J1CCC4DIUSulyUPC961dPxlA+sB5D7GSiY7/NZXA/P8yiXbe5BwK3GKDZPlAQvonj/ufhNo9HH/4jEqvkU599tjFqDPjGQdP7dAhBb+xKDdzPooExi928RHnwCzi1XUnzlZrQ/CLykzQGYHLvFxEkGNAwDNpk0hquuuoJsJks+V8DzXLOw8pJRsZYrIwxDkskkM2bM4Dvf+Q6u6/ZNuImdiyqfjxKgSJRGOSHu4EbUJHDGgVPbiRutJmpfhV60hqCnjepiiKsDcokEOluD29BE1DgUXTUc3VhPuBSipQl06yprtbcVCTte6ZeV7Nv5Mm666SYmTZpEqVQy99c7W/Hf5XHEawmDwLynpq6O5ctXcuYZZ7Bs2TKLjUAQR30AWaWyBPIst38VZ9RmcPKv8C7dm3Ln2xYyF2pTqWRU2b+iCf41X98xcXXl1GmXep2dcKRO/UF813u0S41W3iBNdoJ2MuM0qcGaZKNWbq2J+lUiYTIf++13oF61ulnL6O7u1qVSSQdBoN9rHHvssRYe4Hl99+W42hWtvtnvtLuv1smju3T6xGd15rMX6tQWe2m/ZpT2qdVp6nSWYTrrT9DZ1Ja6KjNF1yQn66wao5M0aV/V6kR2pE5O3E0ndzlPpw54XPt7r9HOrmWd3OIO2Z9x2Nf65b7vm3u5/PLL3/Wey+WyLhTy5hkrY+5bC/X07eK4g5vqjRNgYgTVJgahEk2axCDt4OnU4G11+pc5nf7GE9pTjVr5tSZs/SEjhR/QCDSwbcfm8smSSI3C+dHfjFUcnr8fpXwLKiGFGCKURbS8TI2dqH5B3FiYlWz0KAwYPWY8f/zjH5k+bRvWrl2L7wvgIzaPTLWP6tUMogESiQRdXV1MmzaNhQsX9mkCyQpGIanRp+M0TiZceC10LoDqKvxJ0/A3m0Zq0hTcCePRQ4aQrE4xKOHhO0nW5AoUOrugpZ3S4kXk3ppD8a2X0G8+je7MoZIjUMO/gc4tJFj9G4NbFKvdqu4yRxxxJLff/ifzcy6XM/8GQWD+lftPJBOkU2mDUGtp7eKN117jlRef47rrfsHallYcwTAabWYRRjaZ7BHJJMrLuIhiF64hPf109BnXwY0/Iv/Yj3E8jyjsjqFl/5ICeL8CINa2rJ6LIolKVOEU0yS++hOCQw7F/+ZRFOffQ5QZSaQ8nKjD5MBNwYRJr4rFb1/iD4vZ5nmCxwtobBzEbb//E5/+9G60NLeYie2v/ivHgSx2bW2t+fujjz7Kpz/96V4BsO93zBHjZxI4k/ZH7fhl2GY39OR6omEQVFkvSkoLBEE+VopCyrDKgR4NRcnESh3AGlBLwJnbhjfnacLnf0f4zl0ExraQWGaI47pGlW82eQrPPvc0NTU15PN5mptb8RM+qWSSVDpJqVRm8eKlPDfjOR554AFeev5FlqxYDaoJv24kTmktxfw78ZFiVX8ftkFOaIHEV2DxedxSD8kT/0S446Fw0QGUVs0Q2UdHOVvHqD82AZC8uwU/KrcGHTikt/484bU/w73pJoq3noXODDLlWDoS81legqIVGLSFQ1tPoIKusV8refwgjEil0txw44188egjWLN6tZnggUJg/p9MJmNeIgTnnnsul19+uflZ4P1S0esP/TSJvf5BUJclGgRO3SqcxDLILYXm1bjtbaRzOVJBgFcKTNQyUpq87xBU1xJWVVHIDsJLjCYsjCVqGQKrgbWrULO/Srn5DrsgKiKdyvL4Y48zbfrWdHZ2mcVOpTN0dHYyZ+48nn7yKR67/z5mvvQq3WEOarbB2fQgslUjUGtfprT0ScrdS0xBqgTH7NlfcQn7Gdmi3eLCVh00k8gOw/nxyzhL3qZ05WEEXh4V5GNEUfDxCIANQ4okZnHcanxvJM5P/2IWN/zmwZTpQSeaUFE3OuoCQbeI1R8KPk7g0PYqlZBofwta1HukXRx3GD//2bl85aSTaF6zpp8hJRa2uV2z26trqkmnksYw3HXXXXnppZfwvCRhUCQ19kTUyIOJ2u+D/FzC7pWEXR3ovAAwo/Wrgs3oPwXiXjk46QxONoubGoRKTyZK7gVrHyRYdSv4KcJyget/9WtOO/UUwihiydIVzJr1Ok888iiP3Xsvc96eS5kqmDSN5LQvkhi7OypXIHzxNkqv/ZmgZ7H9ugFQtgp4xuKMrSKwNRIGCylhYUdDYS3pT32V6Oxr4cfnUHz+BrTvooLO2Bh8/wbh+xCA2G+XnS/6M1mNV6jBP/J7hF87Dudb36E46++o6tG2Ti5shjBn4U1RGScKrN/ci8ivhE7XxfQ5eOlplIo+l/3PPpz53fNZu3Y1Tgzjlh1iSrikaEMpamtrqK7K8tLLr7D77rsZq7qCALL4Ohmyuz2UKQixO8tczkTd+i9//8hc/FuRlUDcS7Fh4ii8XMfxCIMSZ5x5FtdcfQXPznief/zlb9z7j7uYt+htwkQtavqepHY6CG/LAwmzg+GNRYQPXEP4wk3oMGdDXcaOWDfi2V8AKvMix4AUyUithC1xNwC7Ug/u+ffByElE39mfUmGRLVzVEiSqxAf0R6QBtEif+KRVENWSHrIb/PY6eHwmxR99m6ghhYocdLDGSKGcR6Y0SocGZRspgT1XfOQN+8qiGwxcatBpFNuW84PzpnDGORexZs0aIxy2eMfaDqINXN+lpjpLU30tP/jRFVx4/jn2KBBUr7FARWiN5NgJNA8rwmcrgvrvfdWHNe0foK3MUG/iypHyNQWTpmzO6Sd9hb/e+nteeOklSokU7p4Hktn3c7D57hSHDrMFxc+/QXT7lQTP3movlR5HUFxrY/8bjOQN1ABG75pqKY9I0MyCq3TTpjaSnjWkxu0Ev7gHdcutFG+/AJ0o28pmgbOZZ40+pACYWj17/pgvTjbi5IeR/O4VRAdtB8d/j/LqV4mqqtGl5RCsNWcRQU9s+Em2LgZXmpt5b4yb46bxRv2G4vJ/cMHZEznjrItZtXpNn1LTmjByKEUh2UyKupoavITP5w/ZnycfezQWgnVVYCX0WjkCYvVKvyjc+ncSL4lkYmUqZPc5UCqT9qrIybRttwNVnzsavfNelAaNIJDyhhyknn8Rbr2OwmO3mKu44w8n0Xgo+dmXE+TeilX0xhanj/+ggjcUITB1E5JlNdnUrC1Lz3WQ+s5thLvvTXTi4QTtr5gkm9hfkapUKX+oQJBY/gLfTpndr4IqEpP3JDp8O/jjTEorlkPdICivxjFqXwoiJahud6oFUfYrzHmvYRC0OcKVl5CY9Ft+cOXPQf2QE792FstWthiXR9Y2kOCH69LeVqag8zQ1JvneFdfx6t470t3dvYGQbOXnfkp/wD3p9d5nwL0ScRQvoyiFHwEJv4bk9jvi7P9Zavc7mPKYMRSlDEAWWUHm1ZdQN99M8Z83AQX8TXdDbfY9SO1P4dHPUu55AyUG5LsuzDpIY9E6Euk0WkMZz0p5WZTXhPZKBH++DnXQPrifPYHof98iSiko2fKz93MMbFQAzNfHZdnCrIFfgyqNhcMPR4ea6OFFUDvI+kxBB1EoZVI23Fupgu17nvenjsxNyxlbmI/bchP+lCv4wdXnUeRnHPmVb7N0ebMRyJDImjpasTKfY3Tg0bTJZE4470dce+7XcMWNNFqgMiqp5n5VSRsaymCIUZ5PJImZUhkngLoRk6je/0CCzxxKx5bbkst4hN3aaPFkFrKz56B+/WuKf7oZTSf+lG3xP3UuJT5HqcfDe+EcymvuNKwk1s/84BE73VvAGqKdPCo5DGpGEiydTfKhx+CIA/Hu/jultmdBqqZMHWOFl0B/UAGIVZBRPUlIZFBRPd6k3QgP2gzngTbC1rKpu1c9K1FRzlr94vNLgsLkuK0EVzTB+3/S0Pi8wepb8Bv2JNryKq687seo5E1s/5kTaF7bTuS6FCMbTShFLu1BgSFlnx2OPo2pD93DzEfuNUIQDRCCgdPZ95zYMLVk5CT7J0UhpZCE4zNkh72oP+IL5Pfen5WDm+jpkdLzIpRcvEGKxKIFuD/6NcXf3UZQXIk3cTyZz1xGWHM8PQsypig4tfyfBAuvMoEzQz3zvhc/xjz001q23iSKS89boGo8FEL0XXfDF/bG2e9w1O/mEGWk7L30nov/rhrAkDG4niniUIkGnNIY3AP2IKpyCGfk0YlOdGElhD1onUMhAI/IWOr27OlTsx+8Hl6uExItvghv2q6UJp/P1b+8ntOdfzBxjyNZvbaVMK7ACXEp52BVkKdmWIpdzv4lb82cTk9bK474z+uo23XvRcsUmx3voEtFsqnBjP/MQdQc/UVWbrsLbyuPXDuwpARpH3dwklTzKtxLf0PxtzeRa19CoqGWmq9dSDjpdPKvDaH0RgiZMilnFeGsM42g2jqDDzL68geOo0ysorewRuY27IEojxq8LeGi5bgzFhN9bh/cu+5HF54AJ44LyCZ4lzL0DSILbFBKZE8IljJEug532KfQ+22CfhvCZW0QzodyCzqSGxEXLCRyKgxaEpmzht/7Q/hs6ChwCXILYOH5eHUNBBPO4Mbbirz8zMO0+42syLmsLPisyLusLnjMWePxxvIC7UPGMOVbP8XVUW9iaaPDFavaIwqKVCfq2eLYU5j6z7sJrvkNL0zag4XLFPmledxiGbchQUrnyPz6WqKDdqXnpxcRdr1D1dFHk7nySfKNl9Dz2BDKbSVUXYhf5cKMrxH0LLKa9ANtgspi9xnNUiYv8DSJu+hKLWGx1WzhqGow3PksalIGb7udUeVqEDshpsYTr8KUHL4/DRADE8TqFd/Ty+IEI1A77Ug4OYX6WQ/0zENHyyHsRIV5Q4Ag0mZuasCDfgisiRGCBOHy2/CG74sedRy5zPH87W8PsWdiFozYhnxPzgAzAjEM8QhWKZygQM9+x1D11D10PPxHlLCCmTKvfk8ogSd5vnKBZKKRUceewqCTT2PV0M2ZvQqiNwNb85kM0dVpUxWeuuvPBDdcTm7eK2ZZ0tO3IXXkxRQyn6XzJTkaSqis4CHBrU3gv3AlxSV32SNUOAE++AT0GoIGI2mTKFaDGUyhFLHm0fllMGgvwqVl/OYC+oCd0E/fg3Z7QHIEJgdj0+XvTwAk2WOo1CTcKb5/NSS3RB88Ea8tInxmGTqchSo2o4MutM6b4I4EqCzIIyZX0B8euSY3LqreeeMcvOE7ETWMpTt1IM88+iqT911NPjOIUkHQcq6xxMNIEZQ07RIo+MpVJGc+QbF1VRxHkGWT0jTxNEokQoeaQ46g/vRzKY+ZyktLoPxCYFBCQjegJVGU9fDfeAn+92J6nrnHLHyyqYbkZ84g2voMOt6uJewIIatQ1ZLECqEmQWLlc5Seu5hQfHhjvf9rw05jf9RJjIAzhZOhTbaVO0GvIGJT9Avd6D3H4I/ZkdLSty1TGhKRFZdywwWuA3SkMTMMFZv4/ymUmzbGnzNha5ieIbw3T7BsLpQXQdAV056IdAngo/cKvTF/+5sPM2xYNsivRM/6Nm6NQtWVaU1N5fUZPmu6I1aWfVYW5TjwWF1yWdOWpLCsRD4zHPfoa8xRYObOUMIIqUOJ9BbTqfrdXwl+eDuL8lNZ/GiB8ooyTkKmKEKnPVKd7SR/8j1KX93DLL5sley0T5M68jFy6YvperoW3VVGCbxMfEAvhDqXpNuCfuAEwjAXxxo+POLOXCUuGzf3J0dszEgmNhg9i9FuK8EcYJCL+tR0VNhk109IN6Q00nx+/e24ziFZSUZICjJhXD8YibvLOFtl+/ASovLLqKDVWP1OnN61YMYKpNsu3Hs4XB/gwcW28Cgvvht/0W9QjQmcqhJdaihr5rh0Fhw6C4p8zqGYc4TnkbDVg4UlSlseQWL74+11wgAvlaX625fg/+ZROqsOof3ePOGiCNdLogILI/PxqXr0n+hvforc7T8mKPaQqBlJ1Z43EG11P53vbEt5VRGVDdDC+OFE4EdoKWwarHAf+ial5nng2azhhx3GMV03piG2luEvEhLLApSF4/A1oqUroQPYc1Pc5KZEEjE0cD3LmPqeAiBSYrl1JfMkH07hCox6j5Ho13LoeW+CXowuye4vGCo0e8bYHS9GSgXo+FEO4/A5LuEz55MqzoEGHydbJigm0MsE2asMwld3KXR3BB0Oeq1GlxXOtsfiCU5gu31I/+QxijtdSOeDGYJXhOvPYu51MTD4+9SylfjXnkDu0s9RWDaXyEviJxtxt7+XzqqTyK2IIFFGZX20J9hChZbQfCbAHeuTmPkriq/8wbKRbtQF/aBWQAXtY1Pitmxd5tkGp0zeoygI5hVEK19DP9OBM60RNXJr0NWmItoAck1K5V2PgL4SBpN0cH10WIczZlP0Jj7qsXeg6yVDlEjYBTpnBEAbNi1zAvdHyH3ohx84EyL1LuWeVnj4a3gNAVFWQdaCObUseJeCLm2AnKpbWDyT+C8+TfiXU0geeTUc9wA9y7el+FQRVRaf34eiuEkObuiTeOp2oit2ovDUb4k834SkVVBEbfY/FGu3NGQPgi2MMq7Uo0qZIPgKJx3ijEqSWvsKwd/P6gWLfDxDllCEwGDLcIThVELvYRe62IruegEeX4CuVjibb4LSQw0szxBu9eYXNioAllHLCoBjpB9vFGr6RBvXeeUNQmcROmhDCSxZrFCTdYuxe3IuVQLs5h8/dj8+ImEQDh7XozTvMZKvXEVihIcjqjdpfX3hD5SgCHnxkRMk5j6O+8yPUIfcTHHMmeRfCYnWhCD4P9mdsviBj9/egveHkynfchSlNjlLBXYdGQs7MfRAok1ORjslELcuI/FeAUIppIJbdn40TOFnuohuOolyvjs2hT6qDSDHqCSD4mrKvl/HcGLLaG6CcIVWVPQO4evPohaXUTtNgsQI48pbhvSKEAwcfb+Jo2EGWqUEoJlBJUeiN2+Et7sJF8xCqXZDYKAjIVSWDJ81AHutS1MpI3ZkVQxr+uAIlXefj4jQcSne9UPS+ZlEI33IRMZcwZNd4eIGHsmVr+OveJxgt1splHejvMBE621mrxRAQeOGCVLzn0D9eheKL95IaGhnrcsoU+Ema2H7awgFoib1LGkXZQRAoTOgUg4I3HGsh/vHMyksnmnJrj7C3d9XUiY4APEoKtHVSnwlZjcXLVzuASGqXD2DaNYS2LoJp3q0hUAJMbbTR7v77kagYcCQXZDEqRkKk6pxZi8lan0LrYVEOWeND9EAlZx6JfFgGLga4nSmpXr7SIdN+FMq5Ij+9FWSI0roOqmojBdFXLiwi4TqpDj5fMo9TeZ8N8wbQvxUCqHk4xd9vGcup/zHfSk1z7UUcwa1JFEzqWcOcaf+kHKjGFISAfTMGpiXaICMg24o405MkHzqZooP3Gi0k5mTj3TIYouWLaHdWhOUM5vNsKraqKvVVsIxlDOeWVhehnppDlG9gxoy3NoBcpyLFhgAhrGj97+sl2BVjrEBdBZ3yAicRohef5MoXG4KPk28P5SERMXViyVetIY31LobUecGqVM+kiEJEc8n99rzZJ74KYktPHSN+OKimjVhTYquwTtTEsPHk/eKNpP4uWgsH797Fd79h1N6+lwCOVakVtHYMfYZ5FhLjN6T8hanEYpQJIU6ViG8DToVme9xqso4E5OkW16jeP0ZhAJe/cjU/oCHtZrLuHs58Jvky+NQi6WocYw7KPaXZSPVqodwzismTOCMG40Tyg1b9d97RPcbzoZKvCLjwmRg/GDRqug5s8EVjJ8FeQp23RYviAqSY8NHJUaYuJIKWyopFj6uIZawTHrh1h8xJJoLk33cGo2uUkTVjongkY4M7Zv2AxuirkqQaH4C597dKS76u7XUEZVYsdYlWKTxE2nUHlcTCmewgHFF/YvBJzu/RuNWh+jxDum6bvjxCZS6Oyzi6GMy/CooJSUhd90FqRFov8FocmvZ22NAsn/GUHV6DJG1as3hbtKEFuyAyejK88YNNfqN9a2CmKDZCMCoDE5HGZbPN2lMSUAYZkyRQMOeKSrfhdRYi10rrY7JWD/O5bcgDoGK5bo6iK45h9HjAsKRCJ+C1QRSTi+2TyJCZXwSdT7JuT8huu8gCm1vWZ1l3CndbyZkF4ckdjqH8vCplq0r4ZhjRa5HlTICEA2PSE128X/+LfJzXjH+/sDU80f+tHFATGjnOoXXHic9xmoDgxOMkdqG41iifgFR52L0osUwZhDKkfIny3xurmFoWfo99oCvsvA7s3wGiz8iAytWEbYsMqFHySyJxEWuhUZJrEBlxph/o+KafysNukTCBCCy4vE7qb/lGqo3c4lqQpysg0476EwJp8klme7Ee+IEyk+eSancw3bb78jmm0+J4+vKXkwM37BMYvS2lHc4h6AQWlSZEJWI2q8CVQ1uk8bdKkHm7zfQ9debCMWV/FgXv885N+6fxGlKrSbw42QnQ7KhN0VshESEWjyzwhpY8DZ6aD1uJiUcdDEULuZb6C/3G/pGk9HzIhhajXpnCarQaiNevSBGZcKMZDZDqTooLjNdNSy67N9HfKylqNN1mPvTCxg06zGcyT5UBaiqEHdsCj//Js5f9qHw+m8NGeuBBx7Ed75zBqed9lUDHZNREQLPdfH2u4aSJAIEY+6LIGHiDUrqCRpCmJKgae7zdP/wDALRfOskmT7OUUFVm8UuLTOaQFVtBYmh9u+mOFLjGCh+ARbNQ1U5UF0NgQGmxRcaeN1+jXcqGDihL40t3cYsatkKi/OPqdON3y/MG1Vb48hZVFhirF9rYa4LvfrYp8V8bzEos+r8k6gSdNJYF3+CT/rNO9C/2Zvcshfw0xlOO+1UvvSl4/BczxSUHHrooQZk6ojrFoVkdjqZ/JjdoUcoXOVYE9Xv2MUX+2Ksx+CgmeK3TqCY77HP+7EYfhsbFcZzbc7/KLcIVe6A+qmolBjfNuZiNq8boJcvtKtRm4ayzalYQ3CDR8A6IAmBQ1clccTnlcYLpm2GSF+AcoRlYytIDiXMvwlSAyASM4DJ8wOigD4Kr+CdhUSXfYP0qBLuH/+H4s8Pp9i5mpGjxvCDSy5h3333w3U9qqqq6enp4ZRTTqW+vpEgKJMaNJJg70sIuywOgZQYfoK91KjqCD04onGohrNPoW3hHBtF/Lft/nXm0syz/BCi83NwymVo2BlECAxUzjanUM3LDTjLra2xGm0je7LfEdAveydwIqmjFzdz9UpbE2R2SzXU74iTnIjqetmcReb4Mf6otQ82eNMf8ajUDPYOqd13HPL3/QM+vwvB7RdR1hG77rY7V/z4ciZN3ATfTzB48BDS6bSpLRw+fASnnHqa2TGJQy+jlB4MxdCEd3VSixdszn1dp0lNTFD1s8tYff8/UL6c+x+1v/9eI57PuF2d+TeyTKhhz+s4YSe6aQ90crg5BrQTojtX44hN2CAIYkEHbTg/s04yKD4TxZ+sTtrv6xAMnqV5pWZzVHoEuuMldKE5jir1hX83RNj8US+8VAsJ7LtSINI3R1IvEFKY/TKB47DddtP53S23MGLkSDzfo6mpyZz78nkpMC2USkydPIHs1D3Jb3M04doyjvjLvjLqX6WFxTHEHe9T/cjdrLzmYusef8xG38ZH/5hLDG8Vy7/cQ9T5Jo4Kcep3sF3R5J2FTlRXgSgrfqxEbqVoxDbFeBcjsCJpRbyqGru7u6QwzkHXTUNVTUW1vQy5t2OokahMe0Vb1vHxLXwF7y9Vt9tuuy2HHXbY+prA2CdSYw/z5s3juRkzmDBhPGPGjDELL9eQ6mMjCErRXYpQe19KeaVreBa09PuRRE9SCEhD9DCf9Mr5dJ/7FQIDeunNd3/o8a9slgpUr/fzZt4lNNoOax5FuRkY8hlI1EHPWoLuVtx01sRtrGG3vpfWu2oGcRSHHQXgSVqIHyQIlUc37IRTtSm64xWivCy+BN9t3N+AKSUELK1ePmLWuf4LL6XWQr5w3XXXcffddzN79mwjDOtOpCFyUIrOzk7OO+97lMtFBg0aZBZeXrL7XQGBBkWGTpqKiqaim43qsy6XgDuE3k+cHCdH9N0vU2xeY57PgDA+gjGwovn9DAsJc4Xt3PRKlDkXzIYkeQS8I+vbQ9T2tPH5Vf3eRFQTFbqIUlkD17Op+/dIB9tosLypRCi8B6HGqdodp3436JqD7nw9DkPaiTeVwnHtmmXOlsRQP4bvdSzOf0XVy8JPnjyZn/3sZ7z88sucfvrpnHfeecydO9cIx4ZoWeR38rdFixZxxhlnkM2mqaqqsotvNIFLMpUgk8pCydYJ6rACapEH1Pj1Ps6V36Lw2nPgf3RGn3y/CO6ECRNobGwcGI/oNwwvgisbQDRWykRcw6BAVBb0texMO/8Gu2lCvUDPMnTro1A1FGp2MQCXSPIgsl6mjc57IoIqtCwltKcNh32UmojueI5IVL9hVJIdIv37kqaRg/xrUr/CD+gncbwEKn65KiEkMgbWbAsznfe98DJJU6ZM4Ve/+pWp/v3GN75BdXW12f2//e1ve9+3sSF/EyH45z//yS9+8QtGjRphPtP/KHAkDyDt48rSsUShxF8uRXgNPv6dP6dw943m3Ddt5v6F0X9h5efK4h977LF86UtfMsao/K4/IYbcW4UIKwxkA5QolwskEj577rU3u+62J0lXcAA5A/bQftogf0wDLJnfHml4+YAB82hdE3e1EciePEPwHqBQcx9yXsTZPYkId78Arc+gXBsDkDo1LYSPrliXZVR+dcx2Kd5GLo43e5Xy2n7GSyVOUKnLW8f1lJq/eEG32WYbvv71r/PFL37RWO0yGVL9K68zzzwzniyrCt+NmEn+JhN8ySWXsP322zNt2nasXLkSz7FC6UjFcCA8/jHxiXAGDZIYwqPk//e7JvUc16W/r4Wu8AVVStMqR5TpLxAbrj/4wQ848cQT2Xrrrc3zVKDrlfdU5kCMVolYir2z8847MX36dO66+x6uvOIqSqU4BS84gEQ9wo2jyFu2M+lRmBNcg/A2xuV5lGO9LNot3JgA9LkacmaIfymfj7pnEqmCwZTJaaOF9s0X3r8IepbjlLsJdZ7Royew006H0tndY4o5hfQhDDWFYg+lYo5IaFPKZZqb1xpqmHUnUHbkLrvswje/+U32339/QwcjQyZRJk7U92WXXcb8+fPNZG255Ta8/vosmxeIjUGZvIpKrbCKyM/FYtH4/cIqIkwenV3dduK1MjufsmD7ApP29dveoXTj8QTlOCAUX6P/a12h3ZgQNjQ00t7ebt4j3/vLX/6SY445xgSimpubSaVS5t4qmkEWWYR+6tSpbLbZZgwZMqT3Wiefcjo33nB9PGHW0JUIrYnLVI9HexKrkf0rgB3BPCzECTtM+Zo0wLCceOsfAX0CIB20TZzYCoJbyFuBMVkz1zJ++YNR6WHGAHE63kIX15jQg0xUW2sL6VSGH//4UsaMHmnvpVS26jwUVix5UI/jjjueu+76Z78qXjuRssAyIQ899BC77babmZTKZMvf5syZwxVXXGF+t/mUKeyz737Mnv2GsRH6L0BFfcrnK3Ry8vmFCxdw5plncOutt5HLF8z7PFdyANIPUKJnEb4YwH89nlLrUnuUCSA1Lkt/tyH2RV1dnTnTZefW19ebsPOrs17j5z/7KcOGDeOuu+4yvEay8GeddRZXX3218WQWL15sFl+E4u9//7s55sxejb9z/vy3+fwXvsBrs17F831T7ib3ZG2rMrqwDNdQ4G5iUFw656IKzSjVYwXYtOCzOI8NjoHU4a7tlCEc9p/5pk7N0NqbuJ92EiO0apqm1ZijtDPhq1o1bG8ZvntZvQWOIy90TU2jvuKqa3U5ZsMKgkhHUWRYsmRcd/2v12f4EtZqx+qrb37zm+b9FcawCqvWgQceWIku6TPPPFOXyyX99ttv66eeekrfcsst+oILLtCDBg3Sruvq6urq3vdWXpXrX3PNT3RXV04vWrRAP/vKEl1zdKfmkLz2T9I6s+1ZhrHbS6Z7Pyf3VldXp6dOnar33XdffcIJJ5jv+uUvf6n/8Y9/6BkzZujFixfrjo6O3meU8dBDD+l02s7l6aefbn6Xz+d1GIbmZ7n3dNp+jzxbLpczf+vp6dFdXV3mPTNmPK9Hjx5j3iNsZOJsDaDMd1ythJJfmmwM3lk7E0/RzqiDNTWbas8fptPXrdSpE28TfJNWbpVZq3elize89MJhT0L7e5yoUy9p7W91tFbpyVqNO0Y7m52r3cH7aMfN9jZjqNCgC2W658UU76B32nU//cKM580C5vJ584CysDNnvaZdL74RQ7OuzKLJZ7beemvzfplI+VcmTMZtt93WOwny7/33378eDZtMXH19vXnPE088oR999FF95ZVX6uOPP15vt912RihECGTSH3/iKd3R0aKff3WZrjtKa/corWv2/L1O2GyW3QCplN5nn33M+++44w79QcbTTz9tPh9zL+i//OUvZnFlDuQ+RbCvv/5687cvfOELulAo6GKxOGDx77vvfl1TK+1pJLSR2CAtv6Gpr1DPixAM20s7m3xdO4MP0H79Njp1U49OHPlzS+nn1by3AJiLSgcMMjox7VCdflnr1J7f1k7DQVpN/JpWg/e33PZm91cEIO6IYT4vp4N0B/E1Y47VjSe+oWcvXK2DckH35HJmQeW1xZbb2AdzLb9dRRs88MADvZyBMlkiBGvWrNGjRo0yiyfvGT16tO7s7DSTKBMnkyYCc8MNN/QuXuU6/cc555zTuyCbbDpZr1yxTL/8+ju6YadbNYMP6/3s1ttsoy+55BK9aNEifeKJJ+qhQ4ea75Hvk0WS+1p3BEGoOzu7dUtLi3755ZfNPVa0jmiPpUuXms/Lvcq9y9h77731QQcd1Psc8vvOjg4r8L//g04kkvEcDdSU6wpAL7egvPw67QzZWzvDj9TJ8UfqzJ8inTzgIumSqJEmGGr9a22gNlDOigR09BgXSY/cDub1oHKLoP3FOAwtRkiF+GnAgWL86HIUke2ZSUswhocXKDYbG5hmWFFYNmflzjt9ijdef9UENVxlDaDjjjuOfffd1wRw5PwWC1k8gIsuvpilS5ca+6BQKLDHHnuYc1L4+CokUmJP3H///b13IWyie++9tyGLEDtA3i+GldgDYmy+NW8uBx10CN09PbS+NY8RQ2o54JSTOe6YY5k+bRqZbJYbbrjBMH+K+ykGqSSQxG6Qn5966in++te/smrVKprXttLa2kpzy1ra2tro6ZHMqYQOfGOfyLkveYdcrqf398uXL2fnnXfh7LPPMkagJKTEI6nKiqF4PV//+tfMXNqA0bvFH/pxCcnPYQmnfRZRdmsYuiNRWqHaWm2R70YKQ9bRAJ5gnjTOYO0P3lknH+/RqbOf1l7NIZqaTbSTGKSVYK+8GtNNY0BPnP5qxXFtZ5B9/qx3+UWkcz3Nur29Qzc3NxuJFwmvqHR5/5Ahg82Ok13Q2tpqdlIQlPXjjz9pjgvRFKIl5DO33367OUrkzO3q7jK7ctWqVXrw4MG9O/xzn/uc2UlyPVGp8p2yMyvXqPwL6F9c/yvd3NLWy+Yp45FHHjHvke+Vs1y+r7293VxPtNKUKVMG2Bei+WpqavSkSZPMS3Z+IiExZYw2kSHPJPcs11i9erXO5Xp6n7e9rc387fuXXGp3veP0arx368zSvx+RZRet1SrZpB1niE7u9B2dvFPr5KbCqjpI40v3EVkn3kUDVPDmkvTICVlyN1GTNNZbaGBRpmrIhHzF3RLf0xYdVmSwchHjkokeWXs3z6/6Ai8ujthuVGRg+z3dOaZtO43q6lp6eqS4VHPxxf/DyJGjaDYkkRIYgVy+yNnnnk0YlHt3U1NTI5/61KcMIaMJlIQhVdkqsyOFTKryPskDVKhi5H2iOcaMHm2scdEmFd/74osv5munnWre29LSYna37OaTTjrJaKWxY8eamEQul+/15+XvEqMQTSbWvhBXykv+O5lMcfjhhxtXtWLF77TTzpRK4spKXMCGf9PZDF3doins/VVVZXn59Xn88KIL8V3hAhDvZGM7vz+JVBx76NUEAtZN4EYd+E01AgMgbF0bM5tLsCNmfDHD3t8GfQNx/cJCGb1sJc6woZCssXSlps5MXrYRY4V2baAA2By9UWELHqLctZTb51UZpEoQhvTkesxCbDN1G/Pwn/70PhxzzLGsXi2QMsgXitTU1vCb39zICzNm4JpQph177LEXI0YMN9eoBFrkGuJi9R9CISvulQ0Vh8YFlUkfM2as+bscL/vs82nOP/88s/CihuX2E4kkp5xyigkhy7Pts88+Rujy+R4jbKViCd/3OPnkkznyiCPMMSOBGhEUeaZvf/vbPP74Y0YQKwK02eZTaG/vMCSSch8ivPPfEo7ABIWCuMea5uZOpmw6ie9dezvl0LqfG3Xb+lVw9cUkbEm/EEkK8jkiRXnTLVEdndDZDtKe1kDq3zMU3EvFZYEWi1agRw7HqR+KE8Z8AdKh03TiFIYOS8dmA0j9EUGiRVzCrpV4bY9w16oUKzotVXy+VDQonG23nWoe4IKLf0BHZxfFYpnuXIGE7zHrzbe49NIf4oof3y9pcsD+BxkugFI5pFQOzL0sX7HSBHis3Fn/X3b8228vwnF8ioUyhYJE3HwmbLKped/IUSP5xS+up7u7QBBoiqUytbX1XHzJ//DAAw+YuIF850EHHWQ+Xy5H5OWsltoCN01zaycrV7ewYuVaFr6znDXNbZxz7nn87ne3ms9WxvTp25tzvbOrh2IpMK/2zm6OPPIInn3hRTxfbIsC+VJA85oWTjtqf/Y767cEYRrP5ubXW55ezFX/Kqw4MRQJugkfJUit0VNgxWK0YBwM13Bcr2+xY+/GDxDX+UgocckKdG0CPWwSUftyEywxsPDAN5y8kckexlrAAA8rsCWbXZSgcmrOnSzd4XgeeEtx6GZlCvmInp48U6ZsyWmnnc6E8ZsY1e97Lp6K6ErU8I3v/IC21mbD8yOCKIGkpsYGpk2fxooVq4yalx1ZX1fHw489Y6jWDdtoLAAyHp0xi11334uOToFvySaQaKVUysBPrrmWxoYmw0ssNyoRu7///U4u//FlZveKhhg9ZjSbTdmSFSvXUJaQruvQk2vj/O99n9WrV5DL58n15Mj1FCgWeujsbO3VLpV7mL7dDuZ9+XyBUMgtq6q5/9nZvD1/Dqd/9RT+8Je7GNZYS1cuh+O4lFYv4eLTDmbRyht467YT8Zyy2WSGd6AffVxv13rJych6mWmXwFnKkGiphlG4Q8ahZt4b9zDeOFxvoAAYAIDthKUTPtHiNYYck022gdmvoXwBo1lggTCFGQugQgQhkURTuBPzAwlCSGyBOTOgtIS/rhjMfmNWUggUq5rb2WLrHdhm2k6sWNUstPeUCwVqm5r4/i8e5IXH/mwt4DDsTZ3KZNY0DKKlrTX+W0RQUFz310fsrYu2MKhlO+584S2ObyvgFov2LOzooq5xEKed/nV23Gl3lq5YZRa1NpPihTmL+Po3vmmZNOIzcs899iaRqmZtc7OZk5rqOh588B/ce/ffB0xZwpcIZpphI0aQ8RNUVdfx+puzSad8pm47jdUtHeTF+KFMp6rllw++YriLVi5dzJnfOI3f/PY2wjAy2kG0alYv5JKvH8DpPTfR+Y8TcJ2IwHDt9ReACvhW4v2i8gWkK+X8gv9zUSO2RDf46EWrCP0KI2mMJVjHc1vHCBTVLrs8Qknp88oOdEsJNXVr3PtGEiaElUnyyrLzI4vKMbQltqjCgpelBMnG+iUUWe5eS2rx4zzf+GXeWKUZXlWmS0CK8i7R58J5U4porPb5+cMFbv/lj/AcbSq5zC3F/+6yx9705PLkCpLYCKjxPW57tZOXn33SAp7jXLeUS4nMLnlnEfcvK3NAukRn4JLLt7PFllPZbvudWLRshTFTqpMRM3pq+c7XzmLt6qUGJyBnt0zsrrvsQWdnN109Ugrn0VNqo65pBJdedR01NVmSyTSpdJZ0JoWfStOYcAkbRnLzLbfw2hsXMnmzbRg8eLg5Lspa0+Br/rjAY9FbLxnSCi+RYOaLz3DxBRfzPz/6AT1rWsyOzuVhUmYR3/zKwfywdCPOvcebGghxvW2XMtl0ruEbtND8mMNZWMj8NG45iTN5BwNwKb2zBu07tqnEeqp+I0eA2cGSOnQCQvFp31qN2nwM1E5ECSWMJ+XIkngQQYhr1/u1TLcL1kvDaQTFf+k+uvb4Eg+sSHP8xBbyRTFVxKsICCJFfSLiT29N4Lrrr8TtmmVoUSX/bhM8ATW1tUydvjNrWrvIl0PSqsSCYAi3vrIAV2oWeylg7HeavdGxjPtbS+wwSJtkVMkkiBRd3Tnjc9d4Ac92bMoF1/yC9lcfwnN9081DhHrUqHFMmrwFK5tbKJVLplaQQo8x6jadNMnUR5gSTfFEIo1bLvKqO45f3zeTN67+gak22mobiTtEOGGPgVe+01HLXW/n8Ve9alkTA5uuvufvtzB83AS+fuoptK9ZYTRsc5fLPk1zePOII/mr8Bg9eApFyW0Y1jPLXGqNwLiLmKSF3aypHXQTQ3Gmbke0vIOoeY1EgeN09oYp49Y5AuyCGQCBgKB0F+5ra9A7jsIdswXR28tQni1ClPZmyrVVt71cgJJajcXILoZkkzxKr72Ik1vAw8FoDu1qNuTROeNGQmOmyGNLh3PFXYvxZv2UwDR+iF2U+Fyftu32DGtqpKu9lZREL0sOv8+PYOX8W0lKqtgUaAR9QicBptYVzFzbwpIRw9lUv0O36XPgEmifXBTxdPtIrnvwFbruvcwkqcJIjhvHPP3+BxxE3ZCh9KxaQyKVpuAkDU5K7KliSZHDI68UHXjIyb8qXcMT77TSdtVX8aOC4THcff9DWF5uYmZrlrltWV5oqae1/TGc5lUGsyhzE0US7HH432uF8j7FZtP3ob5hCPWpkHy5gzPHv0zLYcfxZLqdxB1nE/ppW4pnDgI3ZnEVlJDgMqQGsB4GbYnafBzOI29Avt2WyYkLKGBRg+Lqn5pfRwAqtQcWbloGvwM9e6UtLZs6BbVwLqg2tNOGUnnjc8ZAAMsrJJZozBnQKwaepty1gtSsx5i/08nMak+xZVPOOCulQHPf/CZ+OW8U4YzPokodtmYvjn5Zz0Wx8wGfY06xmpkrfd5q8Xm73WdZQw/pWX83NcgD6/JUbA+UaHj9cWZld+TJNa0sy2XpDk1PKYTks620hsKfTjXazIAp4h0tQiesh1f97g6WdZToVh5dQUBPIUQYY4NQUYoKhFGBQAeURRu6Lv7Mh/BWv0PguPiuyzXX38jS7t/TIYwlUdngKRJdC5DeUDH3dR9PcZTn+svPhsxYaiftQ/3Ug2iatC2bjK5hdLqH5CFn4VTlKfz+IkjVoULR05bGRwsNjBTp+NU40RCczXckbPJg1jtxPWfBILUMrYw5JgcitgeQRZvTU2JDwo6RbESnR+I3HIvzqy+hWjXB9x8hCO5B9SwAQQVLrVokIWMhhha+IPHLK4CS+Dgxi+FQ86nP0XnxH/js2mbOHr+SB9/O8rd5I3ijNU1qwU8JHjrTsH0NgJTFUjBk3Ba0Uk25IKlbCWjkSTlFyq3LCEPZmxWXSLh04++WwI1yCEXGza6Rl21cYZ80hsH3Fna+/5Zv69JQy38Hvf8VbdDP7q2p2ggYVLwA4TGy78vAoM1h031wt/8sySnTCTdx8W+5hO4bL0YlB9udryRFnwavASctpeBTSZ5+DOHUoehTbyZo/RsEi9BRuyGTUpEc3RsFhFQs+LjcWN4si9u9GvVSBxwwCDVqAiwZhWmj6XSjnW7LKG6ZlY0rKOeSdVviIVLnKEqvvUCybQFPR2NZ8UyCFzvrUUtfI/3U2ZQWPWDcnXVJJX3lkEhlWLt4Hj5lMsbwkTPQF5IAizMyC2jRsWKTJP2UOeNN1WyojMuoVbF3AVzlkfAE3+AQFgNK8qzx2Zr2k+bvkRtSFnSNdDLxhAXMWCwDK4mNptHkjckUkjaxe8uQVo4p80JjA/Wb3wqmfwPDxPzjBpJCa69bXsN5+hW8F38t/PS4uxyKc9RJ1Lllem66jiCRtRg/KWXzqtDeILzGqUQ7jIBX1hJ2rEJ7BVQQ22qmjLziP25EACpD0MGG3y4qEUYLYcYy3KOaUDsOQ70zHvy30aVmQyIh6qu3otjAlMvr7yaZ0J6VZGY+SNthX+fF5Xkyr5xP9MjPKBS6baCi38QomckgoOZr5+N8/kRSnVLYYHe0hSkpssVOCjdeytr7/2FAm4I4GjJ1R6qvuFn6RpqG0vXVCVrPPIk1Lz6OY5DAZdJN9Qy+/k6KjUNw5r/Omm8eTSkoGk+i4ae/J9p8GuqdRTR//bOEXV3UXfm/6Gm7EOUEFWVjJOYEDSKSWZ+O7xxP18znGPSj36B32huvVKDlG0fTOe+1GFH0QZDEFSIo4fn1CMW4K+cpv/E0vPEUzh8uMz0JEmPGEixZgsoOt1XZyRqUHoXaehJ6vILrVqD1ApTwNEhIWVhENlKss3GyaJFIIVBQa4jmzsFdsgXuHlmie0YR6HqUYALlCDALL9Jbsuo0MsAxSxodf59jetuVCB65l7qxkyn85rsUF82KO2eIil4HrCgAHaXIT92PXNUYpFNKHBMyRm/QAc0JqD/3NyRefJZC21rTmcs/5yreHjHZarkytA6GQTvsAS8+bjqGGD09dhLLN9+RUgc4u46j5uuXEl59Bt6QETRvugfF4Y1klq+k3N2FU1VNyzb7kG+SjlP2EmYa7clGsruTYPF8VMKjeZu9yQ0ZT3JtM87q5grT7wdY/H5iUAnchBGR6YKVNW5elAvp/OutqERc8y87Wjq0STGIOxFnv6Ho1SX0q6+hndWoUtFuSEMxW+kv+F4CYDpPiUqUUmMBGnagO+fDw22Epw9CTR6Oer7Bdq2wRfgoiVhpiQZUok5xiwgboopp5FyKM5+i/NVHTP2aoTSPiSb7PXp8lAQ4jcMIM+NxmzWZWU8SXn+6cQ9dIpLn/IGe0ZvT01k0DN/CkpH5/FdZPX5n3DVQNeOf5LbYhbDcQGHK9ua+DIm1fMXEadCuUa15ok6fwme/ReaBv1E22MY6/OURzsvPWUzs6E0Iglq8lojM438m+PM1qGppjiHHo4cq9BC0NeONnkCkmnBbI7yZs8i3r7ISskGbYt2IXG9YL3ab45/7CoBiatiyYW5TyQa7bDL3QksjnMB6CM7YsTA9jfrtcsrNr4EjXAJC4S+1gjZu09/637gA9O7eIkoYJ0qdKDWf6MnZOCfuAXvWwfPDUH61YQwjFB66QkwwVenvU5GD/m5hYPrbVW7DMDquO0yOwSord/SWlBhC1KJRnXnUiLEmEu1WNVIqV0HBxVu8jNKapaTGTqR8yPcpr9Bk3n6awoXH4F33Ktptojh4Ck5NA3S12kD10G0IVwsY1DOBn0JPhHvq9SSe+xtdbdIsSqFnS3dwcMZPo1zKELWUKIzfC06fjIpcQyObXvgYuR9/zdyrN24qUVAjDhLMe1OUoCWMquTyKzV9ZlFjX74ScjcMHxX7q/8axOXrWkReFlzEWHa9FIUIg1sK3OqYEHow6tPj0LkI/YAAZRdDuRttehNYATA08xsQx43YADEhoah1QXIkVhMtnInzwFTUDlW4wycRLn3BsolKAEV4ZCQ5ZGDUgmsXG7tkw8PisKgEidox6KphqMxQnNRgQr8JnW7Ay9ai/ARRqgk95zYKb9xsJ3/U9kRtwgFYpmv0/rhf299yOMm8dkJa+vre+2uj2vwvXEZ3VxNeWxlnxkOozbeFtd1m1wdVw0iMnUzptWdQCZ8wvYXpa5VeOAtv5Uvk9vwqBb0p3o5noWX310RES+bZ+rrGLQglltIdocV/c4cQ5cvomirKi2320gSOh2xFcbXxBtEvPW7OKmNE9xtiD8icZqZ+Bz3xs7ilVoJSD2GhCzfXZpm/i2vRuZXo7hUEXYsIBZlcaXRlQtQiCGKUigsobeaFPawWr3ESauc61GMtlOY/D24LSiq6RP2bWH3MK7ABhbRhG6A3IGAZqYWMQKhI9V1voPbamcQOoyksyBpCRWHdMjBl0x4+MvF1g7Ltdc4sqqXUsQTds8K4LpVu43L+i99sjDtRZz1ShyjGnoZhnyJapfHCEv6Ch9HlLvMeySi6Tpnwlb9QmnkHiR0OozD080RLylDlk9/5f3D3g1A4/pcVCYcn8cZvR/TaM3iNwmYyCSV9G5ctoPznM0kN352e1GSTd3ASLm7PEspL55hMpGqYCishUejE/dvxBLlm089Q7l2VenAyNQS5TqLqqeg1Qj0n7KNVJCbtaKJzpit6yiNasZjy6iXGRirM+xMseshSuUj6NlKEQrgp9pa4akIAbVxqC0s3rnkc+TOLj+0dZJpHSzPrYBjutpsSVSncf74EpTkSBjW1Go64lYa7YeMVWhsUgAr5gZw7pglRqZsosRT95nM4L25JuN9Q3HvGEHW8ZVW/cNhFknKUxse2aMOwhRlBEi0gEb2iac05MGRTYcBZRzhr6wmF/aJVkUgtIbr1EAKheItHpdQxUdeA3uvHFFdoEm4PyUVPmEhiVCqQqBlGsWYngnc0ySE7ofgpTtNEyqU6ExhT0ga2VMD5y2kkj3mAovALV4Ffmk+5px01aCQqNdl0xClENST2/ott3CBhFe2SGRQS/np7nHIeaqfAWoVkqKPdbra8SQYSBclB4P/zZEoP3mji90HPMlPCtf5pXJkRcQVlTiuLL//KJrENPCKxuUz3MOkHkMFxB8Nug3Df6CCY+SjaXYUqSg+HnBEkMfzWrQh+bw0gj2mKT4V1UyQxhyp2EAYzcW9/FvWD/XG324LgnschIQEM8c/lLBIJdeIvtSXllWCOpazu17EjnoHeqprYgJRgiD92K5xJI0nJpl/wOnlJ50kJmjmWxP9WeFpTfdwPyY2aRKYD/Gd+TvfdF/ZOamrEZmS+/QolUviN25kSr8SkaTBIkRSl9exMk0Urvv0U2Rd/jLfbJYYShpdfMwLpj9sKNbSJRKeAaeW8TdnupHJ+e4qw8DbRqgUkRm8O40aSyMVIKrHandDaG5IxlWNo4Uv2pkwyx86DeeYBRqKNLZi8Rpy7t6rfJnskIWUKQkVTusLknkTlFO72k3HGZdCX3UPYPQsSbbZtn+EsjHs3vQtb50bbxll/V852STZUo/16VHIQTvJTeD86B6oTRN++mLA003LWm6igUHVbLkHDXmke0MKh3lfbuLjFmFc7mMToCSalHK1eTrF5ee/frLDYSllvwjRC8ZJEKyx+nVJJehfYCfS9BN64LQzTp1suU174Gl7TSKhvMkGaaOkcQkH6mHXzSY3fmiihCFYspNyylmTDUNyh4whlIs0urMhtXA6f6yRYMg8324A7cgKBcbeSdoEFrmfCrkI6mae0YI6pNOpfHrf+PMQULtL/2JQw2PNeQB4m8CW5fhFEIYtMNBoj0C2OxP3BxSYLGHznbMJwhvGRpXegHAF2w/Tv2fgBBMBKgZx3onok5FhjvzgaTmL7o+CyL+H+4h4Kf70anemEkqgdoZITIZCHFQNEiAwDy2gZC8B6PXt6reOBJVcbudn+n1zPy+oPkVqvV9A6lD69S6Hi467/e2Mk0vsZ6wd/N3Df6yB5KuVsA3ojV2BdMdrDVP2aDRgjscxLon7VNkzfWSa1yzHo752A+sEtFB+7AZ1qhVIbKhQPQELklWPzA/YM6rvzSLL+Ziea9iTSldJdS/TK/fDkQqIvfBpfYtbG5ksM6HFlf45dw3chjRJwRzqdGljP5zj4iRSJpH1Js2hB6qx76xUMkiPG4QABivAlMJRMxo0iKlTIDsl0Gi8hhqhLJiPnaJzKFuPOlJP1FYQKdK3ye/M3zyNbVUUqkzHGbiqViMPR9m/WOrffIVjGdDZLVkq9pIV8ImlAozKy2ap+5Wb9gR5xv0Jx+Qw2wx6pBqRiXqIJkqhCF4lUPfrIw1CvrCB8+i5ICY9zLgZ/Srq6Upj77sGo92B0sH3nDDmk7GohIQjaCMvzUL+7BVWbRH3xeNNL2LJHmhZXffjg2Nc1hbzrfnG8A4466ihOPvlUMyEnn3IKO+28s+kofvGFFzJ+3FhGjhjBOeecbybNTFcv9gCy0/cnOWpzy9Hbr3BTFunCCy5m00mbmHP3oosupqa6mgnjx3PZpZeSTacMqPOkr3ylb3pMrNzG6lNjJ1M17dOWDqbCxxtpk+WTur4pm23GxPETufrqa00R55TNN2P3XXcxv99yyhS+d/bZJpL5+cMP56gjjrSFrT/6ERMnTjAkF9/97hnsueeevZqgIgAVjdCLqYif1Ubw5Gcptw9wOlrx9j0cNbiW6JYbKAfz4+Zd8THcCyHjwwpAXwIjMhzBBSsEbo7yvMdRf3kQffB0vC13Q/eUbVxAsIHG0BGJrQQ8KudeBUTaJxGBSvLMs88ZyNWocZszZavpBnnbWQgZMnQci5cs4ZVXX6W9XVLQlRyDeBkR3qSDUI2bV7hTelW8CFN3QVFTN4Qx48ZTP3QcEydviZeu5vW5C+no6KCqdghdhvysn3qMr+8OmYo7/jP9ytqtZyPo4Zmvz2He3PmkUlm6Ch7lQOEm0mz3qX1NwKZQLFE3eIQpLpn1+mxenvmazUwmawyiKZ2to7VbCkxsEWj/JbLPF0O9ZdfEwTQJBonrKcggLUDbMVujDz0C545HCGb9ExK2Xa/NyIoBvy5U/0M1j7Z4NKORxNxy0tYe8LIkkpvi/uRXRIWA8JwTCaSXUGwIWhpzoZWVMLGN9duIVwWZYr82lakm39NJJltlBNfzBdWbo2HwEDrb2igWCqQzWXI9XQPuybqqthuWEFkMfCiHIcNG0dbSjJdwyOcKJFMZU5lkuoxHZepqh5CuyrJKkLPrGBO91vk657SMqupa8rkcnuPhJhLGuCsHJcaMmcSihfPMcdXYOIgVy94hmUoR6ohSscDQEWPp7rLPM2zkOJYufssinntbxcd4fZMRFPdP/H05Avy4Mlu6t+XxhOr+nDvRI8cQnfdFyl1vCrGB6Rcs3ckMb3Ds+n103cPtbNiwpOm1l8JJ1BEV0qS2PxR1+Q/g9/dRFlKFjCCGyhDITZXN0WEJJiuqrdJfoKLurBrcWAl2ZddvMI9eCZZv4Ak2bkia/9+g8dk34t23gWvYe9m4Qdn/uhv6uf8wv4+1ohFok2yyvD9CxBEJ4MM0jBbr30N1rCZ94AWEXzoT9ZOLyT9/G6QKKAmSGaZwidusD/p4t/EBWJ0km2TtAaFe19KuM12m9MI9OH+8m+iLB+BNPwR6JGTaBw+3Nc3vcgPxLrNqT1wgawxJxK0/e8aGb2nDi284/z0x4DwbuTPXrDCK9V3TiQ3EDT1r7xlsW3cOuN9KUUYvS5n5udKi3v6+8nNFwMzzyD15Xvy5ylFYyRv25esN474IqbiDcv/y+c4V+ON2JTj8TLwHHyR4/veoVBklnEHG4JO1Gahd38/4ABpAbixmpjaZqCTaFWs4he8Nxb/iZnT9UKJvH0tp7fOWkELyCCIwcmNmrcTKH6gBNnJXfbhASZ58oLSqzOBAVJENMvGvXcOR1YiZ0Td6jYqNs7HL9UMqmf9z1ivzsnIiwR76LH7jWWSg0E7Sq0ed9biF6//4cMrFxRazIcetJON6Xe0PloL+QLxutp+gDPniku0eokuUcsuJrj4fXZPE+dYleF6T5dQTAiQTRJE8gVrHENzQV9t0sARqqmqGMWT7PeIJW3dyRV1aCpl1h6s0iaFjqfvy96i/5CYyW++GL3Dp9a4gO2v9lq6Wdk2TGL4pNV+4kNrjrqJq1y/h+eKqbkhj2PN6IzNmwC6y+OnqRmo/9xXqjvl2LEzrLlSvKBhjz9LXuwYn6ckuP/JagqGj4cazKHcvsBG+sNCX8NkI6ve9xr9A7Gd3sSGIEuBoqRMSAcW3n0Nf9UOi7bchcdIPUUXxWS2F2brcOhsfIvmQ8JoYddnNlNODjRG1oRIpz/Q07Pd7UyWjSX/mdLLf+gWlYpbcIy+T2P/r1Jx3M44kTnrz1BJrEEYz+V3/q9qz2ktUk9rxq+jVEaU3ZuOO3hlvqwNtYmXAcSSkWT6+17C+IRlrEQmlp8ZtS+qiP1P6xo2UN/9sXPu3vkhavRhT8YtdIFHVYhv+PhcQ7H4w/h9/RHnxg6ika7qF2Ty/JDb+tcU38/jB3l4JxdpJNKSSoYsudhClqig+/L+kR00gOO7LpBbNJn/3ZYTZtDUK46rhfpdZfygX36kie+HNrBDu/mVXkUg3UBa6+v6LrSQLXU1QlAS8haBVRpAdTfGmayjNfxS/cRJR21qC7fclTKdRJVu7b+RADFlH+gfHF4yD75KyTe5wLLplJfknf0pEkXDRc6QOP5towQzKHSsq/VHtR0TL+RljiPe/juk+UjeM5GYHwxEXUHrwWnhtLdHyl2Lnct1wsGySOGdiuBilvV0HiS2OJTjiPBL3307xqZ8RJh1j9Jm5N7mF9+/ybWj8i9SescoxRoekjEOkh7tOhpRu+wHuvY9S/sZ5JHc7Dqen03Ls9nvgPgugnxEkGcQooOqz36A0cXd6ivWkvnyuAXj2GmS9Xy9MNKJZBk6geaDmbvx0A7X7n0n1URdQKi+l1NyJKub7br2i6t3+qlvO6dB8X/TZyylV1xAKmNRLEfUsp7zV0aidjurtYdg3EwqVyKw/sY5L9Z5n4+x+BbniSMJtz8ILXUpP/so+ywaIH0yb+UrYutyBN2Z3ouNvwXvpafJ/PY/QC3FMtC/u2PoubeE/Jg2w/jCYc7mXUII+DqHqpHT9t0gM/xP6/OtIdbaSf/UvBsemTUWR2nBSRM4xL0X3fdfj5RKk9/0yPdd+jbC7eX14lciDIHvXuRNzmebFuI1bUn77MQqzHoV8CW9SNgafxqC+eJLVuiFKY6wBL91H1LnWOhmBMHN6qHnziRbP7pfdjC8lfIOVEvZ+EK7QUeQfuw63nMafcgzJpQvJ/e1UwnK3zfP3e54BGVGx/0s9JIdOh1PuRK+YR3DryUhPWKlQCiPB+fUFqD7s+BDkvtbqtMsZNy6Sm1MRYWkN4Q9PgSVLiC69ifRmBxBKu1nBEcaPaiuKKkkQC3dyxGModeAPHkb00yMJWubZtizrna+2ennAb00pmUPpjb/hDZF2Kk2oUp7MgVdQeunGPk7d3ieXuP3A57HTr8n/8UjCZ67DHzSO9JYHkdns06h7vkth9n1xHUEs9JWPeusshuQGwjL+3t/CdQMSj14MbS+hg3ajdSqh3nWfyqR7gzyJIVuhT7sXOlsIbjyGUn65OeoiwWgaCbVZvn/13B/4tRulIXm/L6ErEbIi+dc3LGNOslG7NOj0kL11+ublOv2PnE5t9hkDEXESVdpxhVxKXp55WbqTmNYyWaedpkn9oxnrfafQp2SGTNFKaNIGUJ7YazjJel118E901dG368Sw7e3vzHv73pPIDNWp6rHx9fvTsci9eOZeM1scrGu+fqdOjNrOvm9d2hbzPNU6OWLb9f5u7n3QVhqnVqOqDPNa3/PId9jvqVC8eH7aNALLDN1Wpy9aq1PfW6YTddO1IqMdoX6R1mXmvirP8ZG9PqrennHwx9DI+zheygipP2ga6uIbYPAw9A+PozjzdlvGbMp/Y7tXB6badpNNNiHhC8AkQvke5WKJXD7HgrfnrxNZc0g1TibfMmeAdhBNKp3Apa9zVCzhJpIE5TyhhFXFY7HvMtnCRGoIjpeh0C1sIH2BKxmSvJHvE6IJUe5N9bXkQm24ffsPkzdIVOPVj6e4epYNOJn0QsTQYcPZdqvN6erJG0ILKRIREgp5lkWLFtrq3gqphqvwghL+6D2ITroD1dWOvuFzFNvnmu4kkmK3IfSPvlfBh7YB+oaopjh2LrXJAiz20xSbZ5K68Hicc68juPBPpH/SQOnJ6y2rpZF5MSaVweQJRaxgL6Uit1Qu0tDYxFtz5vD2/LcG5M9tfkp6Fw5MpMjrmGOOpnHQcMvDqzTZbDWvvfoK99xzZ2+yJf4E/QNM/Tl9R44ezUEHfoZCscCCBYsYPWasKSW7+aYbe8PWJnrZey/rMJVK0eugQXzu2BNpWb2at+cvIJPNsHLFUmbNErYw+WwfA4gTlEhMOYromD+iVr9BcPMxBJ1v2cUPpFLxozH4PmYBkBGnhCsTKwlCv4pS21zci7+M941r0Gf9En/wREp//Z7pRaTEhdJFhg8fzp133GG4fMQeaGhq5LlnnibhulRV19DTvc7uM8DTgUMWb8aLLzF+wmTyubwpAVv2zmJGjR1j8vVRXPtvPi+LGPZdQxa1ko8IShHLlq4w/AC+l+T+++434db+7+lzaYUKpVKaLrasLTCV3994/a+NthGOIKGR7ehoMWnp5rVrLNQrLJkAlb/HRYQHXwyzH0T/4SSi/GoTp9CC6zc+/oYRhJ9AAahk0kS+YyxaqQudSBMWlxBddSrJ4y4g+NKZ+GO3hBu/Sql9AY6f4pDPfZ6mQYMNZ55gC3u62pi2/Y7G6Bk26zXDzFFhCzGnlmHckunrK0XzPY9xo8awYO5s6urqKSdTjJkwju7uTlOP33/YbGUpjvRqQx8zbfqOzJ07h8bGJsPLm61KGcLrKZtPNungHT+1I0E5ZMWKFbz04vM2nyBmY9lCwI13J1HM6lq+9OWv0NbeTaaqylDKNK9ZzYhROxOWyvz0J1caBLFXNRz3kF8R7nAw6uHrCO4+j0DqMaQWUQy+jcLHPsEC0DdsMaV5hLJjgJWB005087kkl7wFp16IHvM8qeu/QnH2HTz88COks2nmvD6LMRM2w/MSlMMSVZks70inLhNbiSdC3CzBva3rDinFplO2ZMo221FVk2H+/AUGmDFpwmY8+eij8TES+9lSNq1LvUGbbLaGKVtuS01DI3V1g0wK1084dLS3m1KtpsFDqMlWMfPlFwbYAgZ6Vm6PjwMb7BI2sGt/8jNKQcDQ4cPp7u4ilfSZPXc+5VwXngRwxu+POuwWIhG2W0+h8PJNRIL2MVLUf/E/3vERGoEbGjaRIzF36UgeiVrz0zgFh+Sk3VDHf59o/KY499xG7g9nQNBsS55kYdaL0a+T8x/AUdg3stU1ZpELUszpOWbn19bW0NZW6Wncd2/0C0kJQYM0ZTA0MWFIrrs9rr8Lqa1vNEyhFRSzaKnejukmp1Ah1rBj/dRvP+SgqiPzmasJdz8Rd8FLhP84lWDVK0RulS0mMRnXj3FJ/r0CIEPOwwqvoG9BDokMuuSRTI3E//y3CfY/EmfJKtTfzqX8wh8Ixef1M9bnNUZipb6w/61ueIf0egrrBlrfIxeh15l0UfmmCNS1huHA0Z8fceDvK/fUWzIv/wZFfKGn3+oE9ME/JmochPvQVRQf/CFh0AVC9x6UPjrf/pMlAHbYOoO4vEli8AJxVlmcoo+/6Y44XzyfaNNNUc89S3THhQQLpYhUNpiQH1aaPa931fV+U1noXvaNOAfxfsgf1EaQyRa40fuH/p/YwFUsh6Kx2kOhvJA6x71Q+12K3npHvAXPEvz9XIIlTxtOH4FvmUqg3hKZj1/t/0cEIP46W+dvikcE5izwspTpauGlR5L41FGEh5yEU5uFZ++C+64gWPx0nK8RCpqYR6A33//BwA8f9bOwjv1hjgyhyNGGlwRv5C6ovc9Cb38IbstKovsuIZjxRwJp5GgKXcq9DaDWbeXyf1QA+h8LFkJtznzJtUt+v+jjNkzG2+so2O9oQ7bkvPAA+uFfEMx7yGTmZGgJp1agYObuBQcXx6HeFQ3bf3e9P9TswFHxcPrj92yzbSmEsbfg4o3fD/b4NkzbByUNHB/9OeXH/5ewR8g2pfxIavYkuNP/WPv37vz/qAAMaF8WF58IbkD70qs1iRP4eEM2x9vlMPReRxqgCXPnwVO3Er78J6KOhX0xMRGcXp9cwJDxpK7Xw/BdCuTe14jhZAJYMb6jQMUlMWNNPK9mLGrro9A7fAk1cTOcnjb0ozcSPft7grZFhKb7qrLFn1KybYy9/8yifwI0wIBb6O1r6wjpkSSMvLSphVPlBF7dRPzpe6N2/RzRuPHo1hD15gPw8t+I3nqKsF2aW5djgRAYlS1QsS9LZFnJ3Q2oK9oIYFP1nveVopY4/WySXZYAyyaoHdzacTgT9kJv+3nU5nuh0x4smYV67naCVx8i6HgH/MhEJKPeog1RGf/u3sOfaAHoK102ECjJEkq6VErIDWLHRwVJnHQT7pitcLc/EGfaLgSD66AlwJn/Cnr2Y0QLniFaMRe6VxFhq5At5Et6GorhKTV7FnFrETdxWNjULlgDzMQIJEchyJ+ogma2GEZFGqd6KAzbFG/szrDF3jB6O6KUwmleiXr9AVMxFb4zi6DUYjrpSI0gQtMSFU1zLZs9/c/v+k+cANhhd22cKY0xe0KEKDaCsGB6hgfXCavwakahJk1Dbb4jzubTiYY12grR9i5YPQ9n6VvopfOJ1iyBtrVEPV2oXMFE7Eyxp8lBxIimGLol2ACDShZiplTSsIqomiFEg8fCiE1xhk5BjZhE1JjGkXD+8nfgjSeI3nyCaPnrhLnVRE7JJHZMs2YDi5d2bRU0NZ/I8QkSgAGIin6YATG0YtdRhMFJmhYohBk0daj0ENzBW+GO3wYmjceZOAY9LEtUbRnULF6yiFvqIMx1EZVzhkDakluWTULKmA1y7HhZ3EQNUUqIlzLWK5PYjPAtrlyDs2A+0aLXCRe/StT8NrqwAtwieHI0WIh2JNVT5oKy2/9Tncb/awVg4OhtQRAXSxpbQdg5BGjqSMvUuFw6StsXg1CZ4ai6EVA/DIaMRA0fijOsjmhQNbohC40e1ErIMK7AFuS6RHbbhZuviNPaA2tbYNUaWLYcLaXpLctMSZYurUXTRqTyliZXIpZhzrKqys+m6WYfQPOTpez/CwVgfWmIhcAEd9zeLibW+BMDUtgzpGeuj9IZtK4Dr9Z215R//TpUsg6dqoZklSW5FFVdyhEVWlB5Ka3uIAra0WEbSguXXBHtFC0GX4hphRdRFtzQ5osfX0kNxzw8/7G4xP91AegdlX3VV1VrsfnCUCKFlLKtU6YCxxArSWbNuIpCrSpHitjvUqZtVb+tXo+ItIBGLchV4FwSnTOLLBFIU9xi1bwAWSyRpu3D2+fF/5dN43+vAKwbhTMtrWM3r1JwItqhYkNIaZittLHehsQI5Aip5PAFmWNRzjYwExMrmYYXNg9hu29XEIP6AxVfftLHf6kAvItQxJ017GLHnc3Mr+KkVOW9vf0NdBwksuwlJulk/P7+YeZKEOnjQeX8J8fHiAf4D41KTN0YkNaD72sI21eQ2VsvqOmXqrXl5tYV7S8A/w3mHP+/a4D3Myp1AetX5ZjxH0rI/CfH/z0N8K7jw+YD+D83/h98snxfHeWBDgAAAABJRU5ErkJggg=="));
}

struct {
    bool enableESP = false;
    bool AimSilent = false;
    bool AimSilent360 = false;
    bool autoswitch = false;

    bool downaimkill = false;
    bool resetguest = false;
    bool telekill = false;
    bool Aimkilltpv2 = false;
    bool Aimkillrotate = false;
    bool Aimkillrotatev2 = false;
    bool Aimkillrotatev3 = false;
    bool Aimkilltp = false;
    bool downplayer = false;
    bool highjump = false;
    bool medikitrun = false;
    bool ultraswitch = false;
    bool speedhackjoy = false;
    bool speedrun = false;
    bool cameraup = false;
    bool wallHack = false;
    bool teleportcar = false;
    bool doublegun = false;
    bool upplayerx = false;
    bool telehack = false;
    bool aimbody = false;
    bool TeleBeta = false;
    bool climbup = false;
    float FlyUp = 0.0f;
    int FlySpeed = 0;
    float vehicle_y = 0.0f;
    float vehicle_unY = 0.0f;
} MasterBool;

struct {
    bool enableAimbot = false;
    bool aimbotShoot = false;
    bool aimbotScope = false;
    bool Aimkill = false;
    bool Aimkill360 = false;
    bool teleprt = false;

    bool Aimkillrage = false;
    bool aimbot = false;
    bool SilentAim = false;
    bool aimbotbody = false;
    bool UnlimitedAmmo = false;
    bool norecoil = false;
    float aimbotFOV = 0.0f;
    float aimbotSmoothness = 20.0f;
    float speedValue = 0.0f;
    bool speedHack = false;
} pAimbotPlayer;

struct {
    bool espLine = false;
    bool espBox = false;
    bool espInfo = false;
    bool espHealth = false;
    bool DISC = false;
    bool espDrawFov = false;
    bool espTracker = false;
    bool espLineTracker = false;
    Color espColor = Color::White();
    Color espnameColor = Color::White();
    bool espNickName = false;
    int lineType = 0;
    int boxType = 0;
} pEspPlayer;

struct {
    bool speedHack = false;
    bool undergroundCatapult = false;
    bool catapultDistance = false;
} pMemoryTools;

using namespace std;

std::string LoggedInOwnerID = "";

bool showAnimation = false;
long long animationStartTime = 0;
int fovCircleSize = 50;
int fovColorMode = 0; // 0 = White, 1 = RGB Rainbow, 2 = Custom ARGB
int fovCustomColor = 0xFFFFFFFF;

int frameCount = 0;
float fpsValue = 0.0f;
long long lastFpsTime = 0;

long long getCurrentTimeMs() {
    return std::chrono::duration_cast<std::chrono::milliseconds>(
        std::chrono::system_clock::now().time_since_epoch()
    ).count();
}

struct FeatureNotification {
    char name[64];
    bool enabled;
    long long startTime;
    bool active;
} currentNotification;

void showNotification(const char* name, bool enabled) {
    strcpy(currentNotification.name, name);
    currentNotification.enabled = enabled;
    currentNotification.startTime = getCurrentTimeMs();
    currentNotification.active = true;
}

// Called from Java to send owner ID

// Show toast from native
void ShowErrorToast(JNIEnv* env, const char* message) {
    jclass cls = env->FindClass("com/vivek/Login");
    if (!cls) return;

    jmethodID method = env->GetStaticMethodID(cls, "showToastFromNative", "(Landroid/content/Context;Ljava/lang/String;)V");
    if (!method) return;

    jfieldID contextField = env->GetStaticFieldID(cls, "globalContext", "Landroid/content/Context;");
    jobject context = env->GetStaticObjectField(cls, contextField);
    if (!context) return;

    jstring jMessage = env->NewStringUTF(message);
    env->CallStaticVoidMethod(cls, method, context, jMessage);
    env->DeleteLocalRef(jMessage);
}


extern "C"
JNIEXPORT void JNICALL
Java_com_vivek_Login_sendOwnerIDToNative(JNIEnv* env, jobject, jstring ownerId) {
    const char *nativeStr = env->GetStringUTFChars(ownerId, 0);
    LoggedInOwnerID = std::string(nativeStr);
    env->ReleaseStringUTFChars(ownerId, nativeStr);

    LOGD("🔒 Owner ID received from Java: %s", LoggedInOwnerID.c_str());

    if (LoggedInOwnerID == "8Z9qRQ2zph") {
    } else {
        LOGD("❌ Blocked features for unknown owner ID: %s", LoggedInOwnerID.c_str());
    }
}



extern "C"
JNIEXPORT void JNICALL
Java_com_vivek_Menu_Init(JNIEnv *env, jclass thiz) {
    startClient();
}

extern "C"
JNIEXPORT void JNICALL
Java_com_vivek_Menu_Functions(JNIEnv *env, jclass clazz) {
    Widget widget = Widget(env);
    widget.Tab("Functions");
    widget.Tab1("Functions");
    // ---------------- Aim Features ----------------
    widget.Category(OBFUSCATE("Aimbot Features"));
    widget.Switch(OBFUSCATE("Activate All"), 102);
    widget.Switch(OBFUSCATE("Silent Aim"), 103);
    widget.Switch(OBFUSCATE("Drag Headshot"), 1055);
    widget.Switch(OBFUSCATE("Sniper Auto Aim"), 500);
    widget.Switch(OBFUSCATE("Show Fov"), 16);
    widget.SeekBar(OBFUSCATE("Adjust Headshot Rate"), 0, 100, "%", 104);
    widget.SeekBar(OBFUSCATE("Adjust FOV Size"), 10, 100, "%", 1077);
    widget.ColorPicker(OBFUSCATE("FOV Color Wheel"), 1078);
}


extern "C"
JNIEXPORT void JNICALL
Java_com_vivek_Menu_ChangesID(JNIEnv *env, jclass clazz, jint id, jint value) {
    switch (id) {


        case 102: { // ENABLE ALL
            if (LoggedInOwnerID.find("8Z9qRQ2zph") != std::string::npos) {

                pAimbotPlayer.enableAimbot = !pAimbotPlayer.enableAimbot;
                SendFeatuere(101, pAimbotPlayer.enableAimbot);
                MasterBool.enableESP = !MasterBool.enableESP;
                SendFeatuere(3, MasterBool.enableESP);

                MasterBool.ultraswitch = !MasterBool.ultraswitch;
                SendFeatuere(212, MasterBool.ultraswitch);

                if (pAimbotPlayer.enableAimbot) {
                    showAnimation = true;
                    animationStartTime = getCurrentTimeMs();
                } else {
                    showAnimation = false;
                }
                showNotification("Activate All", pAimbotPlayer.enableAimbot);
            } else {
                ShowErrorToast(env, "VIVEK PANEL ALWAYS ON TOP ✅.   ");
                LOGD("❌ BLOCKED: Owner ID mismatch! Found: %s", LoggedInOwnerID.c_str());
            }
            break;
        }


        case 103:
            pAimbotPlayer.Aimkill = !pAimbotPlayer.Aimkill;
            SendFeatuere(103, pAimbotPlayer.Aimkill);
            showNotification("Silent Aim", pAimbotPlayer.Aimkill);
            break;
        case 1055:
            pAimbotPlayer.Aimkill360 = !pAimbotPlayer.Aimkill360;
            SendFeatuere(1055, pAimbotPlayer.Aimkill360);
            showNotification("Drag Headshot", pAimbotPlayer.Aimkill360);
            break;
        case 7581:
            pAimbotPlayer.Aimkillrage = !pAimbotPlayer.Aimkillrage;
            SendFeatuere(7581, pAimbotPlayer.Aimkillrage);
            break;
        case 104:
            pAimbotPlayer.aimbotFOV = value;
            SendFOV(104, value);
            break;
        case 1077:
            fovCircleSize = value;
            break;
        case 1078:
            if (value == -1) {
                fovColorMode = 1; // RGB Rainbow Dynamic
            } else {
                fovColorMode = 2; // Custom ARGB color
                fovCustomColor = value;
            }
            break;

        case 105:
            pAimbotPlayer.aimbot = !pAimbotPlayer.aimbot;
            SendFeatuere(105, pAimbotPlayer.aimbot);
            break;

        case 106:
            pAimbotPlayer.norecoil = !pAimbotPlayer.norecoil;
            SendFeatuere(106, pAimbotPlayer.norecoil);
            break;

        case 107:
            pAimbotPlayer.aimbotSmoothness = value;
            SendFOV(107, value);
            break;
        case 1044:
            MasterBool.FlyUp = value;
            SendFOV(1044, value);
            break;
        case 1043:
            MasterBool.FlySpeed = value;
            SendFOV(1043, value);
            break;
        case 108:
            pAimbotPlayer.aimbotbody = !pAimbotPlayer.aimbotbody;
            SendFeatuere(108, pAimbotPlayer.aimbotbody);
            break;

        case 109:
            pAimbotPlayer.speedHack = !pAimbotPlayer.speedHack;
            SendFeatuere(109, pAimbotPlayer.speedHack);
            break;
        case 147:
            pAimbotPlayer.UnlimitedAmmo = !pAimbotPlayer.UnlimitedAmmo;
            SendFeatuere(147, pAimbotPlayer.UnlimitedAmmo);
            break;
        case 110:
            pAimbotPlayer.speedValue = value;
            SendFOV(110, value);
            break;

        case 111:
            pAimbotPlayer.SilentAim = !pAimbotPlayer.SilentAim;
            SendFeatuere(111, pAimbotPlayer.SilentAim);
            break;
        case 550:
            pAimbotPlayer.teleprt = !pAimbotPlayer.teleprt;
            SendFeatuere(550, pAimbotPlayer.teleprt);
            break;

        case 1:
            pEspPlayer.espLine = !pEspPlayer.espLine;
            SendFeatuere(3, pEspPlayer.espLine || pEspPlayer.espBox || pEspPlayer.espNickName || pEspPlayer.espHealth);
            showNotification("ESP Line", pEspPlayer.espLine);
            break;

        case 2:
            pEspPlayer.espBox = !pEspPlayer.espBox;
            SendFeatuere(3, pEspPlayer.espLine || pEspPlayer.espBox || pEspPlayer.espNickName || pEspPlayer.espHealth);
            showNotification("ESP Box", pEspPlayer.espBox);
            break;

        case 3:
            pEspPlayer.espHealth = !pEspPlayer.espHealth;
            SendFeatuere(3, pEspPlayer.espLine || pEspPlayer.espBox || pEspPlayer.espNickName || pEspPlayer.espHealth);
            showNotification("ESP Health", pEspPlayer.espHealth);
            break;
        case 33333:
            pEspPlayer.DISC = !pEspPlayer.DISC;
            break;

        case 4:
            pEspPlayer.espNickName = !pEspPlayer.espNickName;
            SendFeatuere(3, pEspPlayer.espLine || pEspPlayer.espBox || pEspPlayer.espNickName || pEspPlayer.espHealth);
            showNotification("ESP Name", pEspPlayer.espNickName);
            break;

        case 5:
            if (value == 0) {
                pEspPlayer.espColor = Color::White();
            } else if (value == 1) {
                pEspPlayer.espColor = Color::Green();
            } else if (value == 2) {
                pEspPlayer.espColor = Color::Blue();
            } else if (value == 3) {
                pEspPlayer.espColor = Color::Red();
            } else if (value == 4) {
                pEspPlayer.espColor = Color::Black();
            } else if (value == 5) {
                pEspPlayer.espColor = Color::Yellow();
            } else if (value == 6) {
                pEspPlayer.espColor = Color::Cyan();
            } else if (value == 7) {
                pEspPlayer.espColor = Color::Magenta();
            } else if (value == 8) {
                pEspPlayer.espColor = Color::Gray();
            } else if (value == 9) {
                pEspPlayer.espColor = Color::Purple();
            }
            break;

        case 6:
            if (value == 0) {
                pEspPlayer.lineType = value;
            } else if (value == 1) {
                pEspPlayer.lineType = value;
            } else if (value == 2) {
                pEspPlayer.lineType = value;
            }
            break;

        case 7:
            if (value == 0) {
                pEspPlayer.boxType = value;
            } else if (value == 1) {
                pEspPlayer.boxType = value;
            } else if (value == 2) {
                pEspPlayer.boxType = value;
            }
            break;

        case -2:
            pMemoryTools.catapultDistance = !pMemoryTools.catapultDistance;
            SendFeatuere(5, pMemoryTools.catapultDistance);
            break;

        case 16:
            pEspPlayer.espDrawFov = !pEspPlayer.espDrawFov;
            showNotification("Show Fov", pEspPlayer.espDrawFov);
            break;

        case 9:
            pEspPlayer.espHealth = !pEspPlayer.espHealth;
            SendFeatuere(3, pEspPlayer.espLine || pEspPlayer.espBox || pEspPlayer.espNickName || pEspPlayer.espHealth);
            showNotification("ESP Health", pEspPlayer.espHealth);
            break;
        case 14:
            pEspPlayer.espTracker = !pEspPlayer.espTracker;
            break;
        case 144:
            pEspPlayer.espLineTracker = !pEspPlayer.espTracker;
            break;

        case 10:
            MasterBool.ultraswitch = !MasterBool.ultraswitch;
            SendFeatuere(10, MasterBool.ultraswitch);
            break;
        case 11:
            MasterBool.highjump = !MasterBool.highjump;
            SendFeatuere(11, MasterBool.highjump);
            break;
        case 12:
            MasterBool.resetguest = !MasterBool.resetguest;
            SendFeatuere(12, MasterBool.resetguest);
            break;

        case 13:
            MasterBool.medikitrun = !MasterBool.medikitrun;
            SendFeatuere(13, MasterBool.medikitrun);
            break;
        case 1111:
            MasterBool.cameraup = !MasterBool.cameraup;
            SendFeatuere(1111, MasterBool.cameraup);
            break;
        case 15:
            MasterBool.speedhackjoy = !MasterBool.speedhackjoy;
            SendFeatuere(15, MasterBool.speedhackjoy);
            break;
        case 17:
            MasterBool.doublegun = !MasterBool.doublegun;
            SendFeatuere(17, MasterBool.doublegun);
            break;
        case 166:
            MasterBool.wallHack = !MasterBool.wallHack;
            SendFeatuere(166, MasterBool.wallHack);
            break;
        case 19:
            MasterBool.telehack = !MasterBool.telehack;
            SendFeatuere(19, MasterBool.telehack);
            break;
        case 20:
            MasterBool.upplayerx = !MasterBool.upplayerx;
            SendFeatuere(20, MasterBool.upplayerx);
            showNotification("Up Player", MasterBool.upplayerx);
            break;
        case 21:
            MasterBool.aimbody = !MasterBool.aimbody;
            SendFeatuere(21, MasterBool.aimbody);
            break;
        case 22:
            MasterBool.AimSilent = !MasterBool.AimSilent;
            SendFeatuere(22, MasterBool.AimSilent);
            break;
        case 1056:
            MasterBool.AimSilent360 = !MasterBool.AimSilent360;
            SendFeatuere(1056, MasterBool.AimSilent360);
            break;
        case 500:
            MasterBool.Aimkilltp = !MasterBool.Aimkilltp;
            SendFeatuere(500, MasterBool.Aimkilltp);
            showNotification("Sniper Auto Aim", MasterBool.Aimkilltp);
            break;
        case 501:
            MasterBool.Aimkilltpv2 = !MasterBool.Aimkilltpv2;
            SendFeatuere(501, MasterBool.Aimkilltpv2);
            break;
        case 502:
            MasterBool.Aimkillrotate = !MasterBool.Aimkillrotate;
            SendFeatuere(502, MasterBool.Aimkillrotate);
            break;
        case 503:
            MasterBool.Aimkillrotatev2 = !MasterBool.Aimkillrotatev2;
            SendFeatuere(503, MasterBool.Aimkillrotatev2);
            break;
        case 504:
            MasterBool.downaimkill = !MasterBool.downaimkill;
            SendFeatuere(504, MasterBool.downaimkill);
            break;
        case 505:
            MasterBool.autoswitch = !MasterBool.autoswitch;
            SendFeatuere(505, MasterBool.autoswitch);
            break;

        case 506:
            MasterBool.Aimkillrotatev3 = !MasterBool.Aimkillrotatev3;
            SendFeatuere(506, MasterBool.Aimkillrotatev3);
            break;
        case 507:
            MasterBool.speedrun = !MasterBool.speedrun;
            SendFeatuere(507, MasterBool.speedrun);
            break;
        case 508:
            MasterBool.TeleBeta = !MasterBool.TeleBeta;
            SendFeatuere(508, MasterBool.TeleBeta);
            showNotification("Sniper Auto Aim", MasterBool.TeleBeta);
            break;
        case 509:
            MasterBool.climbup = !MasterBool.climbup;
            SendFeatuere(509, MasterBool.climbup);
            break;
    }
}

extern "C"
JNIEXPORT void JNICALL
Java_com_vivek_Menu_OnDrawLoad(JNIEnv *env, jclass clazz, jobject draw_view, jobject canvas) {
    DrawView draw = DrawView(env, draw_view, canvas);

    std::string userLicenseKey = "admin";
    jclass menuClass = env->FindClass("com/vivek/Menu");
    if (menuClass != nullptr) {
        jfieldID keyField = env->GetStaticFieldID(menuClass, "userLicenseKey", "Ljava/lang/String;");
        if (keyField != nullptr) {
            jstring jKeyStr = (jstring) env->GetStaticObjectField(menuClass, keyField);
            if (jKeyStr != nullptr) {
                const char *keyChars = env->GetStringUTFChars(jKeyStr, nullptr);
                if (keyChars != nullptr) {
                    userLicenseKey = std::string(keyChars);
                    env->ReleaseStringUTFChars(jKeyStr, keyChars);
                }
            }
        }
    }

    if (draw.isValid()) {
        long long currentTime = getCurrentTimeMs();
        frameCount++;
        if (currentTime - lastFpsTime >= 1000) {
            fpsValue = frameCount * 1000.0f / (currentTime - lastFpsTime);
            frameCount = 0;
            lastFpsTime = currentTime;
        }

        char fpsText[32];
        sprintf(fpsText, "FPS- %.0f", fpsValue);
        Vector2 fpsPos(30.0f, (float)draw.getHeight() - 40.0f);
        draw.DrawText(Color(0, 0, 0, 200), fpsText, Vector2(fpsPos.X + 2.0f, fpsPos.Y + 2.0f), 30.0f);
        draw.DrawText(Color(0, 210, 255, 255), fpsText, fpsPos, 30.0f);

        // --- Neon/RGB Glowing FOV Circle & Tactical Center Crosshair ---
        if (pEspPlayer.espDrawFov) {
            float radius = 35.0f + ((float)fovCircleSize * 3.5f);
            Vector2 screenCenter((float)draw.getWidth() / 2.0f, (float)draw.getHeight() / 2.0f);

            Color coreColor;
            if (fovColorMode == 1) {
                // Dynamic Continuous RGB Rainbow Spectrum
                float hue = fmod((float)(currentTime % 3000) / 3000.0f, 1.0f);
                coreColor = FromHSB(hue, 1.0f, 1.0f);
            } else if (fovColorMode == 2) {
                // Custom ARGB Color chosen from Color Wheel
                int a = (fovCustomColor >> 24) & 0xFF;
                int r = (fovCustomColor >> 16) & 0xFF;
                int g = (fovCustomColor >> 8) & 0xFF;
                int b = fovCustomColor & 0xFF;
                if (a == 0) a = 255;
                coreColor = Color(r, g, b, a);
            } else {
                // Default White Core
                coreColor = Color::White();
            }

            // Neon Breathing Glow Pulse
            float breath = (sinf((float)currentTime / 280.0f) + 1.0f) * 0.5f; // 0.0f to 1.0f
            Color glowOuter = Color(coreColor.r, coreColor.g, coreColor.b, 30.0f + breath * 35.0f);
            Color glowInner = Color(coreColor.r, coreColor.g, coreColor.b, 70.0f + breath * 55.0f);

            draw.DrawCircle(glowOuter, 8.0f, screenCenter, radius + 2.5f);
            draw.DrawCircle(glowInner, 5.0f, screenCenter, radius + 1.0f);
            draw.DrawCircle(coreColor, 3.5f, screenCenter, radius);

            // Tactical Sniper Center Dot (Glowing Core)
            draw.DrawCircle(Color(coreColor.r, coreColor.g, coreColor.b, 120), 4.0f, screenCenter, 3.5f);
            draw.DrawCircle(Color(255, 255, 255, 255), 2.2f, screenCenter, 1.8f);

            // 4-Axis Tactical Crosshair Ticks (Left, Right, Top, Bottom)
            float tickGap = 7.0f;
            float tickLen = 12.0f;
            float tickThick = 2.0f;
            Color tickColor(coreColor.r, coreColor.g, coreColor.b, 230);
            draw.DrawLine(tickColor, tickThick, Vector2(screenCenter.X - tickGap - tickLen, screenCenter.Y), Vector2(screenCenter.X - tickGap, screenCenter.Y));
            draw.DrawLine(tickColor, tickThick, Vector2(screenCenter.X + tickGap, screenCenter.Y), Vector2(screenCenter.X + tickGap + tickLen, screenCenter.Y));
            draw.DrawLine(tickColor, tickThick, Vector2(screenCenter.X, screenCenter.Y - tickGap - tickLen), Vector2(screenCenter.X, screenCenter.Y - tickGap));
            draw.DrawLine(tickColor, tickThick, Vector2(screenCenter.X, screenCenter.Y + tickGap), Vector2(screenCenter.X, screenCenter.Y + tickGap + tickLen));
        }

        // --- 4-Second Activation Loading Sequence with Checkmark, GOOD TO GO & Success Audio ---
        if (showAnimation) {
            long long elapsed = getCurrentTimeMs() - animationStartTime;
            long long loadDuration = 4000; // 4.0s progress from 0% to 100%
            long long holdDuration = 1200; // 1.2s hold displaying Checkmark + "GOOD TO GO" + chime
            long long fadeDuration = 600;  // 0.6s smooth dissolve fade into game

            const char *brandName = "VIVEK PANEL";

            if (elapsed < loadDuration) {
                // Phase 1: 0% to 100% loading with dynamic feature cycling (4.0s)
                float progress = (float)elapsed / (float)loadDuration;
                draw.DrawActivationLoading(brandName, progress, false, 1.0f);
            }
            else if (elapsed < loadDuration + holdDuration) {
                // Phase 2: Complete! Glowing green checkmark + "GOOD TO GO" + audio chime
                draw.DrawActivationLoading(brandName, 1.0f, true, 1.0f);
            }
            else if (elapsed < loadDuration + holdDuration + fadeDuration) {
                // Phase 3: Smooth dissolve fade-out into game
                long long fadeElapsed = elapsed - (loadDuration + holdDuration);
                float fadeProgress = (float)fadeElapsed / (float)fadeDuration;
                if (fadeProgress > 1.0f) fadeProgress = 1.0f;
                float smoothFade = fadeProgress * fadeProgress * (3.0f - 2.0f * fadeProgress);
                float alpha = 1.0f - smoothFade;
                draw.DrawActivationLoading(brandName, 1.0f, true, alpha);
            }
            else {
                // Animation finished!
                showAnimation = false;
            }
        }

        // Show Logo overlay at top center when Activate All is ON and animation is not running
        if (pAimbotPlayer.enableAimbot && !showAnimation) {
            draw.DrawLogo(draw.getWidth() / 2.0f, 75.0f, 110.0f, 110.0f, 255.0f);
        }

        if (pAimbotPlayer.enableAimbot) {
            Response response = getData(draw.getWidth(), draw.getHeight());

            if (response.Success) {
            for (int i = 0; i < response.PlayerCount; ++i) {
                PlayerData data = response.Players[i];

                Vector3 HeadLoc = data.headPosition;
                Vector3 PesLoc = data.bottomPlayerPosition;

                if (HeadLoc.Z < -1) continue;
                if (PesLoc.Z < -1) continue;

                float distance = data.distance;
                float health = data.health;
                bool IsCaido = data.isDieing;

                // Limit scale for ESP
                float scale = std::max(0.5f, std::min(1.0f, 500.0f / distance));

                // Calculate player box dimensions
                float boxHeight = abs(HeadLoc.Y - PesLoc.Y) * scale;
                float boxWidth = boxHeight * 0.50f;

                // Adjust position for head alignment
                Rect PlayerRect(HeadLoc.X - (boxWidth / 2), draw.getHeight() - HeadLoc.Y, boxWidth, boxHeight);

                if (pEspPlayer.espLine) {
                    Vector2 lineStart;
                    Vector2 lineEnd;

                    if (pEspPlayer.lineType == 0) {
                        lineStart = Vector2(draw.getWidth() / 2, 130.0f);
                        lineEnd = Vector2(HeadLoc.X, draw.getHeight() - HeadLoc.Y);
                    } else if (pEspPlayer.lineType == 1) {
                        lineStart = Vector2(draw.getWidth() / 2, draw.getHeight() / 2);
                        lineEnd = Vector2(HeadLoc.X, draw.getHeight() - HeadLoc.Y);
                    } else if (pEspPlayer.lineType == 2) {
                        lineStart = Vector2(draw.getWidth() / 2, draw.getHeight());
                        lineEnd = Vector2(PesLoc.X, draw.getHeight() - PesLoc.Y);
                    }

                    if (IsCaido) {
                        draw.DrawLine(Color::Red(), 3.5f, lineStart, lineEnd);
                    } else {
                        draw.DrawLine(pEspPlayer.espColor, 3.5f, lineStart, lineEnd);
                    }
                }

                if (pEspPlayer.espBox) {
                    if (IsCaido) {
                        if (pEspPlayer.boxType == 0) {
                            // Draw red glowing border
                            Rect glowRect(PlayerRect.x - 1, PlayerRect.y - 1, PlayerRect.w + 2, PlayerRect.h + 2);
                            draw.DrawBox(Color(255, 0, 0, 45), 5.5f, glowRect);
                            draw.DrawBox(Color::Red(), 2.5f, PlayerRect);
                        } else if (pEspPlayer.boxType == 1) {
                            draw.DrawBox3D(Color::Red(), 2.5f, PlayerRect, 10);
                        } else if (pEspPlayer.boxType == 2) {
                            draw.DrawCornerBox(Color::Red(), 2.5f, PlayerRect, 4, 4);
                        }
                    } else {
                        if (pEspPlayer.boxType == 0) {
                            // Draw customizable color glowing border
                            Rect glowRect(PlayerRect.x - 1, PlayerRect.y - 1, PlayerRect.w + 2, PlayerRect.h + 2);
                            Color glowColor = pEspPlayer.espColor;
                            glowColor.a = 45;
                            draw.DrawBox(glowColor, 5.5f, glowRect);
                            draw.DrawBox(pEspPlayer.espColor, 2.5f, PlayerRect);
                        } else if (pEspPlayer.boxType == 1) {
                            draw.DrawBox3D(pEspPlayer.espColor, 2.5f, PlayerRect, 10);
                        } else if (pEspPlayer.boxType == 2) {
                            draw.DrawCornerBox(pEspPlayer.espColor, 2.5f, PlayerRect, 4, 4);
                        }
                    }
                }

                // ======= Draw Nickname =======
                if(pEspPlayer.espNickName)
                {
                    if (!IsCaido) {

                        Vector2 namePos(HeadLoc.X, draw.getHeight() - HeadLoc.Y - 20);
                        std::string playerName = data.name;
                        draw.DrawTextWithShadow(pEspPlayer.espColor, playerName.c_str(), namePos, 16, Vector2(2, 2), 0.5f);

                    }
                }
                // ======= Draw Distance =======
                if (pEspPlayer.DISC) {
                    float centerX = draw.getWidth() / 2.0f;
                    float centerY = draw.getHeight() / 2.0f;

                    if (!IsCaido) {
                        Vector2 namePos(PlayerRect.x + (PlayerRect.w / 2), PlayerRect.y - (5.0f * scale));
                        namePos.X -= (strlen(data.name) * 2.5f * scale);
                        float textSize = 12.0f * scale;
                        Vector2 shadowOffset(1.0f, 1.0f);
                        char distanceText[32];
                        sprintf(distanceText, "%dm", static_cast<int>(data.distance));

                        // Calculate centered position for distance text
                        float textWidth = strlen(distanceText) * 6.0f * scale; // Approximate text width
                        Vector2 distancePos(
                                PlayerRect.x + (PlayerRect.w / 2) - (textWidth / 2),
                                PlayerRect.y + PlayerRect.h + (18.0f * scale) // Increased from 12.0f to 18.0f to move it further down
                        );

                        // Draw black border
                        draw.DrawTextWithShadow(Color(0, 0, 0, 255), distanceText, Vector2(distancePos.X - 1, distancePos.Y), textSize, shadowOffset, 2.0f);
                        draw.DrawTextWithShadow(Color(0, 0, 0, 255), distanceText, Vector2(distancePos.X + 1, distancePos.Y), textSize, shadowOffset, 2.0f);
                        draw.DrawTextWithShadow(Color(0, 0, 0, 255), distanceText, Vector2(distancePos.X, distancePos.Y - 1), textSize, shadowOffset, 2.0f);
                        draw.DrawTextWithShadow(Color(0, 0, 0, 255), distanceText, Vector2(distancePos.X, distancePos.Y + 1), textSize, shadowOffset, 2.0f);

                        // Draw main text
                        draw.DrawTextWithShadow(Color(255, 255, 255, 255), distanceText, distancePos, textSize, shadowOffset, 2.0f);
                    }
                }





                // ======= Health Bar =======
                if (pEspPlayer.espHealth && !IsCaido) {
                    Vector2 healthBarPos(PlayerRect.x - 5.0f * scale, PlayerRect.y);
                    float healthBarHeight = boxHeight;
                    draw.DrawVerticalHealthBar(healthBarPos, healthBarHeight, 200.0f, data.health);
                }
            }
        } else {
            // Draw simulated mock players for testing preview when not connected to daemon
            int simulatedCount = 2;
            for (int i = 0; i < simulatedCount; ++i) {
                float headX, headY, bottomX, bottomY, distance, health;
                const char* name;

                if (i == 0) {
                    headX = draw.getWidth() * 0.70f;
                    headY = draw.getHeight() * 0.40f;
                    bottomX = draw.getWidth() * 0.70f;
                    bottomY = draw.getHeight() * 0.65f;
                    distance = 45.0f;
                    health = 200.0f;
                    name = "Training BOT 1";
                } else {
                    headX = draw.getWidth() * 0.30f;
                    headY = draw.getHeight() * 0.30f;
                    bottomX = draw.getWidth() * 0.30f;
                    bottomY = draw.getHeight() * 0.75f;
                    distance = 15.0f;
                    health = 100.0f;
                    name = "Training BOT 2";
                }

                float scale = std::max(0.5f, std::min(1.0f, 500.0f / distance));
                float boxHeight = abs(headY - bottomY) * scale;
                float boxWidth = boxHeight * 0.50f;

                Rect PlayerRect(headX - (boxWidth / 2), headY, boxWidth, boxHeight);

                if (pEspPlayer.espLine) {
                    Vector2 lineStart;
                    Vector2 lineEnd(headX, headY);

                    if (pEspPlayer.lineType == 0) {
                        lineStart = Vector2(draw.getWidth() / 2, 130.0f);
                    } else if (pEspPlayer.lineType == 1) {
                        lineStart = Vector2(draw.getWidth() / 2, draw.getHeight() / 2);
                    } else {
                        lineStart = Vector2(draw.getWidth() / 2, draw.getHeight());
                        lineEnd = Vector2(bottomX, bottomY);
                    }

                    draw.DrawLine(pEspPlayer.espColor, 3.5f, lineStart, lineEnd);
                }

                if (pEspPlayer.espBox) {
                    if (pEspPlayer.boxType == 0) {
                        // Draw customizable color glowing border
                        Rect glowRect(PlayerRect.x - 1, PlayerRect.y - 1, PlayerRect.w + 2, PlayerRect.h + 2);
                        Color glowColor = pEspPlayer.espColor;
                        glowColor.a = 45;
                        draw.DrawBox(glowColor, 5.5f, glowRect);
                        draw.DrawBox(pEspPlayer.espColor, 2.5f, PlayerRect);
                    } else if (pEspPlayer.boxType == 1) {
                        draw.DrawBox3D(pEspPlayer.espColor, 2.5f, PlayerRect, 10);
                    } else if (pEspPlayer.boxType == 2) {
                        draw.DrawCornerBox(pEspPlayer.espColor, 2.5f, PlayerRect, 4, 4);
                    }
                }

                if (pEspPlayer.espNickName) {
                    Vector2 namePos(headX, headY - 20);
                    draw.DrawTextWithShadow(pEspPlayer.espColor, name, namePos, 16, Vector2(2, 2), 0.5f);
                }

                if (pEspPlayer.espHealth) {
                    Vector2 healthBarPos(PlayerRect.x - 5.0f * scale, PlayerRect.y);
                    float healthBarHeight = boxHeight;
                    draw.DrawVerticalHealthBar(healthBarPos, healthBarHeight, 200.0f, health);
                }
            }
        }
    }


        // --- Premium Bottom-Right Notification Toast ---
        if (currentNotification.active) {
            long long elapsed = currentTime - currentNotification.startTime;
            if (elapsed < 2500) {
                int alpha = 255;
                if (elapsed < 300) {
                    alpha = (int)(255 * (elapsed / 300.0f));
                } else if (elapsed > 2200) {
                    alpha = (int)(255 * ((2500 - elapsed) / 300.0f));
                }
                if (alpha < 0) alpha = 0;
                if (alpha > 255) alpha = 255;

                float toastWidth = 360.0f;
                float toastHeight = 85.0f;
                float toastX = (float)draw.getWidth() - toastWidth - 30.0f;
                float toastY = (float)draw.getHeight() - toastHeight - 50.0f;

                if (elapsed < 300) {
                    float progress = elapsed / 300.0f;
                    toastX = (float)draw.getWidth() - (toastWidth + 30.0f) * progress;
                } else if (elapsed > 2200) {
                    float progress = (2500 - elapsed) / 300.0f;
                    toastX = (float)draw.getWidth() - (toastWidth + 30.0f) * progress;
                }

                // 1. Draw card background (semi-transparent dark)
                draw.DrawFilledRectinfo(Color(20, 20, 20, (int)(alpha * 0.92f)), Rect(toastX, toastY, toastWidth, toastHeight));

                // 2. Draw card outline box (Gold VIP theme border)
                Color outlineColor = Color(0, 210, 255, alpha);
                draw.DrawBox(outlineColor, 1.5f, Rect(toastX, toastY, toastWidth, toastHeight));

                // 3. Draw thick left accent stripe
                draw.DrawFilledRectinfo(outlineColor, Rect(toastX, toastY, 6.0f, toastHeight));

                // 4. Draw Bell / Star Emoji on the left
                draw.DrawText(Color(255, 255, 255, alpha), "⚡", Vector2(toastX + 35.0f, toastY + 53.0f), 28.0f);

                // 5. Draw Title: "VIVEK PANEL" in bold gold (left-aligned)
                draw.DrawTextLeft(Color(0, 0, 0, (int)(alpha * 0.8f)), "VIVEK PANEL", Vector2(toastX + 70.0f + 1.0f, toastY + 28.0f + 1.0f), 12.0f);
                draw.DrawTextLeft(outlineColor, "VIVEK PANEL", Vector2(toastX + 70.0f, toastY + 28.0f), 12.0f);

                // 6. Draw Status Message: "[Feature] : ACTIVE" (left-aligned)
                char statusText[96];
                if (currentNotification.enabled) {
                    sprintf(statusText, "%s : ACTIVE 🟢", currentNotification.name);
                } else {
                    sprintf(statusText, "%s : OFF ⚪", currentNotification.name);
                }

                Color textColor = currentNotification.enabled ? Color(0, 230, 118, alpha) : Color(180, 180, 180, alpha);

                draw.DrawTextLeft(Color(0, 0, 0, (int)(alpha * 0.8f)), statusText, Vector2(toastX + 70.0f + 1.0f, toastY + 58.0f + 1.0f), 18.0f);
                draw.DrawTextLeft(textColor, statusText, Vector2(toastX + 70.0f, toastY + 58.0f), 18.0f);
            } else {
                currentNotification.active = false;
            }
        }

        // ESP Line Tracker and Name Tracker removed as per user request

    }
}